<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2009 The Kuali Foundation

    Licensed under the Educational Community License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may	obtain a copy of the License at

     http://www.osedu.org/licenses/ECL-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->


<project>
 <modelVersion>4.0.0</modelVersion>
 <groupId>org.kuali.student.mojo</groupId>
 <artifactId>maven-kscontractdoc-plugin</artifactId>
 <packaging>maven-plugin</packaging>
 <version>0.0.1-SNAPSHOT</version>
 <name>KS Contract Documentation Generator</name>
 <properties>
  <cxf.version>2.2.10</cxf.version>
  <kuali.site.download.path>org/kuali/student/mojo</kuali.site.download.path>
  <kuali.site.path>student/mojo/${project.version}</kuali.site.path>
 </properties>
 <url>${kuali.site.public.url}</url>
 <distributionManagement>
  <site>
   <id>${kuali.site.server.id}</id>
   <name>Maven Site</name>
   <url>${kuali.site.publish.url}</url>
  </site>
 </distributionManagement>
 <repositories>
  <repository>
   <id>kuali.nexus</id>
   <name>Nexus Repository Manager</name>
   <url>http://nexus.kuali.org/content/groups/public</url>
   <releases>
    <enabled>true</enabled>
   </releases>
   <snapshots>
    <enabled>true</enabled>
   </snapshots>
  </repository>
 </repositories>
 <!--  <configuration>
 <commonDirectory>https://test.kuali.org/svn/student/sandbox/ks-r2-poc/trunk/ks-services/ks-services-api/src/main/java</commonDirectory>
 <coreDirectory>C:/Users/sambit/kuali/code/trunk/ks-common/ks-common-api/src/main/java</coreDirectory>
 <lumDirectory>C:/Users/sambit/kuali/code/trunk/ks-lum/ks-lum-api/src/main/jav</lumDirectory>
 <htmlDirectory>target/html</htmlDirectory>
</configuration>
 -->
 <dependencies>
  <dependency>
   <groupId>org.apache.maven</groupId>
   <artifactId>maven-plugin-api</artifactId>
   <version>2.0</version>
  </dependency>
  <dependency>
   <groupId>com.sun.xsom</groupId>
   <artifactId>xsom</artifactId>
   <version>20100725</version>
  </dependency>
  <dependency>
   <groupId>com.thoughtworks.qdox</groupId>
   <artifactId>qdox</artifactId>
   <version>1.12</version>
  </dependency>
  <dependency>
   <groupId>junit</groupId>
   <artifactId>junit</artifactId>
   <version>4.5</version>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>org.apache.maven</groupId>
   <artifactId>maven-plugin-api</artifactId>
   <version>2.0</version>
  </dependency>
 </dependencies>

 <build>
  <plugins>
   <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
     <source>1.6</source>
     <target>1.6</target>
    </configuration>
   </plugin>
  </plugins>
 </build>
</project>