package com.sigmasys.kuali.ksa.model.security;

/**
 * KSA Access Control permission constants.
 *
 * @author Michael Ivanov
 */
public enum Permission {

    // Tag permissions
    CREATE_TAG,
    EDIT_TAG,
    CREATE_ADMIN_TAG,
    EDIT_ADMIN_TAG,
    ASSIGN_TAG_TO_TRANSACTION,
    ASSIGN_TAG_TO_TRANSACTION_TYPE,
    ASSIGN_ADMIN_TAG_TO_TRANSACTION,
    ASSIGN_ADMIN_TAG_TO_TRANSACTION_TYPE,

    // Allocation permissions
    CREATE_ALLOCATION,
    REMOVE_ALLOCATION,
    CREATE_LOCKED_ALLOCATION,
    REMOVE_LOCKED_ALLOCATION,
    CREATE_INTERNALLY_LOCKED_ALLOCATION,
    REMOVE_INTERNALLY_LOCKED_ALLOCATION,
    READ_ALLOCATION,

    // Cash limit permissions
    CREATE_CASH_LIMIT_PARAMETER,
    EDIT_CASH_LIMIT_PARAMETER,
    READ_CASH_LIMIT_PARAMETER,
    CHECK_CASH_LIMIT,

    // UI tab permissions
    VIEW_ADMINISTRATION_TAB,
    VIEW_REPORTING_TAB,
    VIEW_COLLECTIONS_TAB,
    VIEW_BATCH_TAB,
    VIEW_THIRD_PARTY_TAB,
    VIEW_SETTINGS_TAB,
    VIEW_ADVANCED_SEARCH,
    VIEW_QUICK_VIEW,

    // Account permissions
    CREATE_ACCOUNT,
    UPDATE_ACCOUNT,
    DELETE_ACCOUNT,
    READ_ACCOUNT,
    AGE_DEBT,
    READ_BALANCE,
    WRITE_OFF_ACCOUNT,
    VIEW_ACCOUNT_PROTECTED_INFO,
    REBALANCE_ACCOUNT,
    READ_ACH,
    CREATE_ACCOUNT_BLOCK_OVERRIDE,
    READ_ACCOUNT_BLOCK_OVERRIDE,
    RELEASE_ACCOUNT_BLOCK_OVERRIDE,
    DELETE_ACCOUNT_BLOCK_OVERRIDE,

    // Currency permissions
    EDIT_CURRENCY,
    READ_CURRENCY,

    // General Ledger permissions
    CREATE_GL_TYPE,
    EDIT_GL_TYPE,
    READ_GL_TYPE,
    CREATE_GL_TRANSACTION,
    EDIT_GL_TRANSACTION,
    READ_GL_TRANSACTION,
    SUMMARIZE_GL_TRANSACTIONS,
    EDIT_GL_SETTINGS,
    READ_GL_REPORT,
    CREATE_GL_TRANSMISSION,
    EXPORT_GL_TRANSACTIONS,
    READ_GL_TRANSMISSION,
    CREATE_GL_BREAKDOWN,
    READ_GL_BREAKDOWN,

    // Failed GL transaction permissions
    READ_FAILED_GL_TRANSACTION,

    // Memo permissions
    READ_MEMO,
    CREATE_MEMO,
    UPDATE_MEMO,
    DELETE_MEMO,
    EXPIRE_MEMO,

    // Alert permissions
    READ_ALERT,
    CREATE_ALERT,
    UPDATE_ALERT,
    DELETE_ALERT,
    EXPIRE_ALERT,

    // Flag permissions
    READ_FLAG,
    CREATE_FLAG,
    UPDATE_FLAG,
    DELETE_FLAG,
    EXPIRE_FLAG,

    // FlagType permissions
    READ_FLAG_TYPE,
    CREATE_FLAG_TYPE,
    UPDATE_FLAG_TYPE,
    DELETE_FLAG_TYPE,

    // InformationAccessLevel permissions
    READ_ACCESS_LEVEL,
    CREATE_ACCESS_LEVEL,
    UPDATE_ACCESS_LEVEL,
    DELETE_ACCESS_LEVEL,

    // Transaction permissions
    IMPORT_TRANSACTIONS,
    CREATE_CHARGE,
    CREATE_PAYMENT,
    CREATE_DEFERMENT,
    REVERSE_TRANSACTION,
    EXPIRE_DEFERMENT,
    WRITE_OFF_TRANSACTION,
    BOUNCE_PAYMENT,
    CONTEST_CHARGE,
    CANCEL_CHARGE,
    DISCOUNT_CHARGE,
    EDIT_TRANSACTION,
    READ_TRANSACTION,
    TRANSFER_TRANSACTION,
    REVERSE_TRANSFER_TRANSACTION,
    EXPORT_CASH_LIMIT_EVENT,

    // Transaction Type permissions
    CREATE_TRANSACTION_TYPE,
    EDIT_TRANSACTION_TYPE,
    READ_TRANSACTION_TYPE,
    ASSIGN_TRANSACTION_TYPE_TO_ROLE,

    // Rollup permissions
    CREATE_ROLLUP,
    EDIT_ROLLUP,
    READ_ROLLUP,

    // Ban type permissions
    CREATE_BANK_TYPE,
    EDIT_BANK_TYPE,

    // Identity type permissions
    CREATE_IDENTITY_TYPE,
    EDIT_IDENTITY_TYPE,

    // Tax type permissions
    CREATE_TAX_TYPE,
    EDIT_TAX_TYPE,

    // Account status type permissions
    CREATE_ACCOUNT_STATUS_TYPE,
    EDIT_ACCOUNT_STATUS_TYPE,

    // Account type permissions
    CREATE_ACCOUNT_TYPE,
    EDIT_ACCOUNT_TYPE,

    // Activity type permissions
    CREATE_ACTIVITY_TYPE,
    EDIT_ACTIVITY_TYPE,

    // Refund and refund type permissions
    CREATE_REFUND_TYPE,
    EDIT_REFUND_TYPE,
    READ_REFUND_TYPE,
    PERFORM_REFUND,
    READ_REFUND,
    REQUEST_REFUND,
    VALIDATE_REFUND,
    CANCEL_REFUND,


    // Transfer type permissions
    CREATE_TRANSFER_TYPE,
    READ_TRANSFER_TYPE,
    UPDATE_TRANSFER_TYPE,
    DELETE_TRANSFER_TYPE,

    // Transaction Transfer permissions
    CREATE_TRANSACTION_TRANSFER,
    READ_TRANSACTION_TRANSFER,
    UPDATE_TRANSACTION_TRANSFER,
    DELETE_TRANSACTION_TRANSFER,
    REVERSE_TRANSACTION_TRANSFER,

    // Payment application permissions
    RUN_PAYMENT_APPLICATION,
    APPLY_PAYMENTS,

    // 1098T permissions
    GENERATE_IRS_1098_T,
    READ_IRS_1098_T,

    // 8300 permissions
    GENERATE_IRS_8300,
    READ_IRS_8300,

    // Bill permissions
    GENERATE_BILL,
    CREATE_BILL_RECORD,
    READ_BILL,
    DELETE_BILL,
    UPDATE_BILL,


    // Report permissions
    GENERATE_AGED_BALANCE_REPORT,
    READ_BATCH_FAILED_REPORT,
    READ_ACCOUNT_REPORT,
    READ_RECEIPT,

    // Third party permissions
    CREATE_THIRD_PARTY_PLAN,
    CREATE_THIRD_PARTY_PLAN_MEMBER,
    CREATE_THIRD_PARTY_ALLOWABLE_CHARGE,
    GENERATE_THIRD_PARTY_TRANSFER,
    REVERSE_THIRD_PARTY_TRANSFER,
    READ_THIRD_PARTY_ALLOWABLE_CHARGE,
    READ_THIRD_PARTY_PLAN,
    READ_THIRD_PARTY_PLAN_MEMBER,
    DELETE_THIRD_PARTY_PLAN_MEMBER,
    READ_THIRD_PARTY_TRANSFER_DETAIL,

    // Payment billing permissions
    CREATE_PAYMENT_BILLING_PLAN,
    CREATE_PAYMENT_BILLING_ALLOWABLE_CHARGE,
    GENERATE_PAYMENT_BILLING_TRANSFER,
    GENERATE_PAYMENT_BILLING_SCHEDULE,
    GENERATE_PAYMENT_BILLING_TRANSACTIONS,
    REVERSE_PAYMENT_BILLING_TRANSFER,
    PROCESS_PAYMENT_BILLING_QUEUE,
    CREATE_PAYMENT_BILLING_QUEUE,
    DELETE_PAYMENT_BILLING_QUEUE,
    CREATE_PAYMENT_BILLING_DATE,
    UPDATE_PAYMENT_BILLING_PLAN,
    UPDATE_PAYMENT_BILLING_TRANSFER,
    READ_PAYMENT_BILLING_ALLOWABLE_CHARGE,
    READ_PAYMENT_BILLING_PLAN,
    READ_PAYMENT_BILLING_TRANSFER_DETAIL,
    READ_PAYMENT_BILLING_TRANSACTION,
    READ_PAYMENT_BILLING_SCHEDULE,
    READ_PAYMENT_BILLING_QUEUE,
    READ_PAYMENT_BILLING_DATE,

    // CreditPermission permissions
    CREATE_CREDIT_PERMISSION,
    UPDATE_CREDIT_PERMISSION,
    READ_CREDIT_PERMISSION,
    DELETE_CREDIT_PERMISSION,

    // Rate permissions
    CREATE_RATE,
    UPDATE_RATE,
    DELETE_RATE,
    READ_RATE,
    CREATE_RATE_TYPE,
    UPDATE_RATE_TYPE,
    DELETE_RATE_TYPE,
    READ_RATE_TYPE,
    CREATE_RATE_CATALOG,
    UPDATE_RATE_CATALOG,
    DELETE_RATE_CATALOG,
    READ_RATE_CATALOG,
    DELETE_RATE_AMOUNT,
    VALIDATE_RATE_TYPE,
    VALIDATE_RATE_CATALOG,
    VALIDATE_RATE,

    // Fee Management permissions:
    READ_FM_MANIFEST,
    DELETE_FM_QUEUE,
    RUN_FEE_ASSESSMENT
}
