
package org.collegeboard.inas._2012;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.collegeboard.inas._2012.input.NeedAnalysisInput;
import org.collegeboard.inas._2012.output.NeedAnalysisOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "INeedAnalysisXmlEngine", targetNamespace = "http://INAS.collegeboard.org/2012/")
@XmlSeeAlso({
    org.collegeboard.inas.faults.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.collegeboard.inas._2012.ObjectFactory.class,
    org.collegeboard.inas._2012.input.ObjectFactory.class,
    org.collegeboard.inas._2012.output.ObjectFactory.class
})
public interface INeedAnalysisXmlEngine {


    /**
     * 
     * @param input
     * @return
     *     returns org.collegeboard.inas._2012.output.NeedAnalysisOutput
     * @throws INeedAnalysisXmlEngineRunNeedAnalysisUnsupportedYearFaultFaultFaultMessage
     * @throws INeedAnalysisXmlEngineRunNeedAnalysisInvalidXmlSchemaFaultFaultFaultMessage
     * @throws INeedAnalysisXmlEngineRunNeedAnalysisServerFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RunNeedAnalysis", action = "http://INAS.collegeboard.org/2012/INeedAnalysisXmlEngine/RunNeedAnalysis")
    @WebResult(name = "RunNeedAnalysisResult", targetNamespace = "http://INAS.collegeboard.org/2012/")
    @RequestWrapper(localName = "RunNeedAnalysis", targetNamespace = "http://INAS.collegeboard.org/2012/", className = "org.collegeboard.inas._2012.RunNeedAnalysis")
    @ResponseWrapper(localName = "RunNeedAnalysisResponse", targetNamespace = "http://INAS.collegeboard.org/2012/", className = "org.collegeboard.inas._2012.RunNeedAnalysisResponse")
    public NeedAnalysisOutput runNeedAnalysis(
        @WebParam(name = "input", targetNamespace = "http://INAS.collegeboard.org/2012/")
        NeedAnalysisInput input)
        throws INeedAnalysisXmlEngineRunNeedAnalysisInvalidXmlSchemaFaultFaultFaultMessage, INeedAnalysisXmlEngineRunNeedAnalysisServerFaultFaultFaultMessage, INeedAnalysisXmlEngineRunNeedAnalysisUnsupportedYearFaultFaultFaultMessage
    ;

}
