--KSEN_ORG
ALTER TABLE KSOR_ORG RENAME TO KSEN_ORG
/
ALTER TABLE KSEN_ORG RENAME COLUMN TYPE TO ORG_TYPE
/
ALTER TABLE KSEN_ORG RENAME COLUMN ST TO ORG_STATE
/
ALTER TABLE KSEN_ORG RENAME COLUMN LNG_NAME TO LONG_NAME
/
ALTER TABLE KSEN_ORG RENAME COLUMN LNG_DESCR TO LONG_DESCR_PLAIN
/
ALTER TABLE KSEN_ORG RENAME COLUMN SHRT_NAME TO SHORT_NAME
/
ALTER TABLE KSEN_ORG RENAME COLUMN SHRT_DESCR TO SHORT_DESCR_PLAIN
/
ALTER TABLE KSEN_ORG ADD (LONG_DESCR_FORMATTED VARCHAR2(4000) NULL,
                          SORT_NAME VARCHAR2(255) NULL,
                          SHORT_DESCR_FORMATTED VARCHAR2(4000) NULL)
/
--remove foreign key constraint that points to a custom type table that is no longer needed
ALTER TABLE KSEN_ORG DROP CONSTRAINT KSOR_ORG_FK1
/

--Move types from custom org type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
SELECT TYPE_KEY, NAME, TYPE_DESC, 'http://student.kuali.org/wsdl/organization/OrgInfo', 'http://student.kuali.org/wsdl/organization/OrganizationService', EFF_DT, EXPIR_DT, VER_NBR, 'SYSTEMLOADER',TO_DATE('20130731', 'YYYYMMDD')
FROM KSOR_ORG_TYPE WHERE TYPE_KEY NOT IN (SELECT TYPE_KEY FROM KSEN_TYPE)
/
--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
SELECT SYS_GUID() ID, attr.OWNER, attr.ATTR_NAME, attr.ATTR_VALUE
FROM KSOR_ORG_TYPE_ATTR attr
WHERE NOT EXISTS (SELECT 'X' FROM KSEN_TYPE_ATTR attrInner WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_ATTR
ALTER TABLE KSOR_ORG_ATTR RENAME TO KSEN_ORG_ATTR
/
ALTER TABLE KSEN_ORG_ATTR RENAME COLUMN OWNER TO OWNER_ID
/
ALTER TABLE KSEN_ORG_ATTR RENAME COLUMN ATTR_NAME TO ATTR_KEY
/
ALTER TABLE KSEN_ORG_ATTR DROP COLUMN VER_NBR
/
ALTER TABLE KSEN_ORG_ATTR MODIFY ATTR_VALUE VARCHAR2(4000)
/

--KSEN_ORG_CD
CREATE TABLE KSEN_ORG_CD
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_CD_TYPE          VARCHAR2(255) NOT NULL ,
	ORG_CD_STATE         VARCHAR2(255) NOT NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	VALUE                VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL
)
/

ALTER TABLE KSEN_ORG_CD
	ADD CONSTRAINT  KSEN_ORG_CD_P PRIMARY KEY (ID)
/

DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_CD_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_CD_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/


CREATE TABLE KSEN_ORG_CD_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL
)
/


ALTER TABLE KSEN_ORG_CD_ATTR
	ADD CONSTRAINT  KSEN_ORG_CD_ATTR_P PRIMARY KEY (ID)
/


--KSEN_ORG_ORG_RELTN
ALTER TABLE KSOR_ORG_ORG_RELTN RENAME TO KSEN_ORG_ORG_RELTN
/
ALTER TABLE KSEN_ORG_ORG_RELTN RENAME COLUMN TYPE TO ORG_RELTN_TYPE
/
ALTER TABLE KSEN_ORG_ORG_RELTN RENAME COLUMN ST TO ORG_RELTN_STATE
/
ALTER TABLE KSEN_ORG_ORG_RELTN RENAME COLUMN ORG TO ORG_ID
/
ALTER TABLE KSEN_ORG_ORG_RELTN RENAME COLUMN RELATED_ORG TO RELATED_ORG_ID
/
--remove foreign key constraint that points to a custom type table that is no longer needed
ALTER TABLE KSEN_ORG_ORG_RELTN DROP CONSTRAINT KSOR_ORG_ORG_RELTN_FK3
/
--Move types from custom org org relation type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
SELECT TYPE_KEY, NAME, TYPE_DESC, 'http://student.kuali.org/wsdl/organization/OrgOrgRelationInfo', 'http://student.kuali.org/wsdl/organization/OrganizationService', EFF_DT, EXPIR_DT, VER_NBR, 'SYSTEMLOADER',TO_DATE('20130731', 'YYYYMMDD')
FROM KSOR_ORG_ORG_RELTN_TYPE WHERE TYPE_KEY NOT IN (SELECT TYPE_KEY FROM KSEN_TYPE)
/
--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
SELECT SYS_GUID() ID, attr.OWNER, attr.ATTR_NAME, attr.ATTR_VALUE
FROM KSOR_ORG_ORG_RELTN_TYPE_ATTR attr
WHERE NOT EXISTS (SELECT 'X' FROM KSEN_TYPE_ATTR attrInner WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_ORG_REL_ATTR
ALTER TABLE KSOR_ORG_ORG_RELTN_ATTR RENAME TO KSEN_ORG_ORG_REL_ATTR
/
ALTER TABLE KSEN_ORG_ORG_REL_ATTR RENAME COLUMN OWNER TO OWNER_ID
/
ALTER TABLE KSEN_ORG_ORG_REL_ATTR RENAME COLUMN ATTR_NAME TO ATTR_KEY
/
ALTER TABLE KSEN_ORG_ORG_REL_ATTR DROP COLUMN VER_NBR
/
ALTER TABLE KSEN_ORG_ORG_REL_ATTR MODIFY ATTR_VALUE VARCHAR2(4000)
/

--KSEN_ORG_HIRCHY
ALTER TABLE KSOR_ORG_HIRCHY RENAME TO KSEN_ORG_HIRCHY
/
ALTER TABLE KSEN_ORG_HIRCHY RENAME COLUMN DESCR TO DESCR_PLAIN
/
ALTER TABLE KSEN_ORG_HIRCHY RENAME COLUMN ROOT_ORG TO ROOT_ORG_ID
/
ALTER TABLE KSEN_ORG_HIRCHY ADD (ORG_HIRCHY_TYPE VARCHAR2(255) NULL,
                                 ORG_HIRCHY_STATE VARCHAR2(255) NULL,
                                 DESCR_FORMATTED VARCHAR2(4000) NULL,
                                 CREATETIME TIMESTAMP(6) NULL,
                                 CREATEID VARCHAR2(255) NULL,
                                 UPDATETIME TIMESTAMP(6) NULL,
                                 UPDATEID VARCHAR2(255) NULL)
/
UPDATE KSEN_ORG_HIRCHY SET ORG_HIRCHY_TYPE=ID, ORG_HIRCHY_STATE='kuali.org.hierarchy.state.active', CREATEID='SYSTEMLOADER',CREATETIME=TO_DATE('20130731', 'YYYYMMDD')
/
ALTER TABLE KSEN_ORG_HIRCHY MODIFY (ORG_HIRCHY_TYPE VARCHAR2(255) NOT NULL,
                                    ORG_HIRCHY_STATE VARCHAR2(255) NOT NULL,
                                    CREATETIME TIMESTAMP(6) NOT NULL,
                                    CREATEID VARCHAR2(255) NOT NULL)
/

--insert org hierarchy type
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
SELECT ORG_HIRCHY_TYPE, NAME, 'http://student.kuali.org/wsdl/organization/OrgHierarchyInfo', 'http://student.kuali.org/wsdl/organization/OrganizationService', EFF_DT, EXPIR_DT, 1, 'SYSTEMLOADER',TO_DATE('20130731', 'YYYYMMDD')
FROM KSEN_ORG_HIRCHY WHERE ORG_HIRCHY_TYPE NOT IN (SELECT TYPE_KEY FROM KSEN_TYPE)
/

--KSEN_ORG_HIRCHY_ATTR
ALTER TABLE KSOR_ORG_HIRCHY_ATTR RENAME TO KSEN_ORG_HIRCHY_ATTR
/
ALTER TABLE KSEN_ORG_HIRCHY_ATTR RENAME COLUMN OWNER TO OWNER_ID
/
ALTER TABLE KSEN_ORG_HIRCHY_ATTR RENAME COLUMN ATTR_NAME TO ATTR_KEY
/
ALTER TABLE KSEN_ORG_HIRCHY_ATTR DROP COLUMN VER_NBR
/
ALTER TABLE KSEN_ORG_HIRCHY_ATTR MODIFY ATTR_VALUE VARCHAR2(4000)
/


--KSEN_ORG_HIRCHY_OORT
CREATE TABLE KSEN_ORG_HIRCHY_OORT
(
	ORG_HIRCHY_ID        VARCHAR2(255) NOT NULL ,
	ORG_ORG_RELTN_TYPE_ID VARCHAR2(255) NOT NULL
)
/


ALTER TABLE KSEN_ORG_HIRCHY_OORT
	ADD CONSTRAINT  KSEN_ORG_HIRCHY_OORT_P PRIMARY KEY (ORG_HIRCHY_ID,ORG_ORG_RELTN_TYPE_ID)
/

--INSERT INTO KSEN_ORG_HIRCHY_OORT
INSERT INTO KSEN_ORG_HIRCHY_OORT
(ORG_HIRCHY_ID, ORG_ORG_RELTN_TYPE_ID)
SELECT DISTINCT ORG_HIRCHY_ID, OOR_TYPE
FROM (SELECT DISTINCT ORG.ORG_TYPE, oor.ORG_RELTN_TYPE OOR_TYPE
      FROM KSEN_ORG ORG, KSEN_ORG_ORG_RELTN OOR
      WHERE (OOR.ORG_ID = ORG.ID OR OOR.RELATED_ORG_ID = ORG.ID)) TABLE1
INNER JOIN
      (SELECT * FROM KSOR_ORG_HIRCHY_JN_ORG_TYPE) TABLE2
ON TABLE1.ORG_TYPE = TABLE2.ORG_TYPE_ID
/

--KSEN_ORG_PERS_RELTN
ALTER TABLE KSOR_ORG_PERS_RELTN RENAME TO KSEN_ORG_PERS_RELTN
/
ALTER TABLE KSEN_ORG_PERS_RELTN RENAME COLUMN ST TO ORG_PERS_RELTN_STATE
/
ALTER TABLE KSEN_ORG_PERS_RELTN RENAME COLUMN ORG TO ORG_ID
/
--remove foreign key constraint that points to a custom type table that is no longer needed
ALTER TABLE KSEN_ORG_PERS_RELTN DROP CONSTRAINT KSOR_ORG_PERS_RELTN_FK2
/
--Move types from custom org person relation type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
SELECT TYPE_KEY, NAME, TYPE_DESC, 'http://student.kuali.org/wsdl/organization/OrgPersonRelationInfo', 'http://student.kuali.org/wsdl/organization/OrganizationService', EFF_DT, EXPIR_DT, VER_NBR, 'SYSTEMLOADER',TO_DATE('20130731', 'YYYYMMDD')
FROM KSOR_ORG_PERS_RELTN_TYPE WHERE TYPE_KEY NOT IN (SELECT TYPE_KEY FROM KSEN_TYPE)
/
--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
SELECT SYS_GUID() ID, attr.OWNER, attr.ATTR_NAME, attr.ATTR_VALUE
FROM KSOR_ORG_PERS_RELTN_TYPE_ATTR attr
WHERE NOT EXISTS (SELECT 'X' FROM KSEN_TYPE_ATTR attrInner WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_PERS_REL_ATTR
ALTER TABLE KSOR_ORG_PERS_RELTN_ATTR RENAME TO KSEN_ORG_PERS_REL_ATTR
/
ALTER TABLE KSEN_ORG_PERS_REL_ATTR RENAME COLUMN OWNER TO OWNER_ID
/
ALTER TABLE KSEN_ORG_PERS_REL_ATTR RENAME COLUMN ATTR_NAME TO ATTR_KEY
/
ALTER TABLE KSEN_ORG_PERS_REL_ATTR DROP COLUMN VER_NBR
/
ALTER TABLE KSEN_ORG_PERS_REL_ATTR MODIFY ATTR_VALUE VARCHAR2(4000)
/

--KSEN_ORG_POS_RESTR
ALTER TABLE KSOR_ORG_POS_RESTR RENAME TO KSEN_ORG_POS_RESTR
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN ORG TO ORG_ID
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN PERS_RELTN_TYPE TO ORG_PERS_RELTN_TYPE
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN TTL TO TITLE
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN DESCR TO DESCR_PLAIN
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN ATP_DUR_TYP_KEY TO STD_DUR_TYPE
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN TM_QUANTITY TO STD_DUR_TIME_QTY
/
ALTER TABLE KSEN_ORG_POS_RESTR RENAME COLUMN MIN_NUM_RELTN TO MIN_NUM_REL
/
ALTER TABLE KSEN_ORG_POS_RESTR ADD DESCR_FORMATTED VARCHAR2(4000) NULL
/
ALTER TABLE KSEN_ORG_POS_RESTR ADD MAX_NUM_REL NUMBER
/
UPDATE KSEN_ORG_POS_RESTR
SET MAX_NUM_REL = MAX_NUM_RELTN
/
ALTER TABLE KSEN_ORG_POS_RESTR DROP COLUMN MAX_NUM_RELTN
/
ALTER TABLE KSEN_ORG_POS_RESTR MODIFY (STD_DUR_TIME_QTY NUMBER,
                                       MIN_NUM_REL NUMBER)
/
--remove foreign key constraint that points to a custom type table that is no longer needed
ALTER TABLE KSEN_ORG_POS_RESTR DROP CONSTRAINT KSOR_ORG_POS_RESTR_FK1
/

--KSEN_ORG_POS_RESTR
ALTER TABLE KSOR_ORG_POS_RESTR_ATTR RENAME TO KSEN_ORG_POS_RESTR_ATTR
/
ALTER TABLE KSEN_ORG_POS_RESTR_ATTR RENAME COLUMN OWNER TO OWNER_ID
/
ALTER TABLE KSEN_ORG_POS_RESTR_ATTR RENAME COLUMN ATTR_NAME TO ATTR_KEY
/
ALTER TABLE KSEN_ORG_POS_RESTR_ATTR DROP COLUMN VER_NBR
/
ALTER TABLE KSEN_ORG_POS_RESTR_ATTR MODIFY ATTR_VALUE VARCHAR2(4000)
/

--DROP TABLES
DROP TABLE KSOR_ORG_JN_ORG_PERS_REL_TYPE
/
DROP TABLE KSOR_ORG_HIRCHY_JN_ORG_TYPE
/
DROP TABLE KSOR_ORG_TYPE_JN_ORG_PERRL_TYP
/
DROP TABLE KSOR_ORG_TYPE_ATTR
/
DROP TABLE KSOR_ORG_TYPE
/
DROP TABLE KSOR_ORG_ORG_RELTN_TYPE_ATTR
/
DROP TABLE KSOR_ORG_ORG_RELTN_TYPE
/
DROP TABLE KSOR_ORG_PERS_RELTN_TYPE_ATTR
/
DROP TABLE KSOR_ORG_PERS_RELTN_TYPE
/

