INSERT INTO KRIM_ENTITY_NM_T (ENTITY_NM_ID,ENTITY_ID,OBJ_ID,VER_NBR,NM_TYP_CD,FIRST_NM,MIDDLE_NM,LAST_NM,SUFFIX_NM,TITLE_NM,DFLT_IND,ACTV_IND,LAST_UPDT_DT)
VALUES (KRIM_ENTITY_NM_ID_S.NEXTVAL,'KS-1535',SYS_GUID(),1,'PRFR','alice',null,'alice','','Ms.','Y','Y',sysdate)
/
INSERT INTO KRIM_ENTITY_AFLTN_T (ENTITY_AFLTN_ID,ENTITY_ID,OBJ_ID,VER_NBR,AFLTN_TYP_CD,CAMPUS_CD,DFLT_IND,ACTV_IND,LAST_UPDT_DT)
VALUES (KRIM_ENTITY_AFLTN_ID_S.NEXTVAL,'KS-1535',SYS_GUID(),0,'STAFF','EA','Y','Y',sysdate)
/
INSERT INTO KRIM_ROLE_MBR_T (ACTV_FRM_DT,ACTV_TO_DT,LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
VALUES (null,null,sysdate,'alice', 'P', SYS_GUID(),(select role_id from KRIM_ROLE_T where ROLE_NM='Kuali Student CM Admin'),KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
