update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-10296'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-5964'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-7158'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-1972'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-12220'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-9779'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-11874'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-11627'
/
update KRIM_ENTITY_AFLTN_T set AFLTN_TYP_CD = 'STDNT', CAMPUS_CD = 'AL' where ENTITY_ID = 'KS-8403'
/
