---Update Term, link conflict resolution to exam Free form text term Spec
UPDATE KRMS_TERM_T T
SET T.TERM_SPEC_ID = (SELECT TERM_SPEC_ID FROM KRMS_TERM_SPEC_T WHERE NM ='ExamFreeFormText')
WHERE T.TERM_ID = 'KS-KRMS-TERM-13489'
/
UPDATE KRMS_TERM_T T
SET T.TERM_SPEC_ID = (SELECT TERM_SPEC_ID FROM KRMS_TERM_SPEC_T WHERE NM ='ExamFreeFormText')
WHERE T.TERM_ID = 'KS-KRMS-TERM-13488'
/
