--KSEN_ORG
INSERT INTO KSEN_ORG
(ID, OBJ_ID, ORG_TYPE, ORG_STATE, LONG_NAME, LONG_DESCR_PLAIN,
 SHORT_NAME, SHORT_DESCR_PLAIN, EXPIR_DT, EFF_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID)
  SELECT
    ID,
    OBJ_ID,
    TYPE,
    COALESCE(ST, 'ACTIVE'),
    LNG_NAME,
    LNG_DESCR,
    SHRT_NAME,
    SHRT_DESCR,
    EXPIR_DT,
    EFF_DT,
    VER_NBR,
    COALESCE(CREATETIME, SYSDATE),
    COALESCE(CREATEID, 'SYSTEMLOADER'),
    UPDATETIME,
    UPDATEID
  FROM KSOR_ORG
/

--Move types from custom org type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
  SELECT
    TYPE_KEY,
    NAME,
    TYPE_DESC,
    'http://student.kuali.org/wsdl/organization/OrgInfo',
    'http://student.kuali.org/wsdl/organization/OrganizationService',
    EFF_DT,
    EXPIR_DT,
    VER_NBR,
    'SYSTEMLOADER',
    TO_DATE('20130731', 'YYYYMMDD')
  FROM KSOR_ORG_TYPE
  WHERE TYPE_KEY NOT IN (SELECT
                           TYPE_KEY
                         FROM KSEN_TYPE)
/
--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
  SELECT
    SYS_GUID() ID,
    attr.OWNER,
    attr.ATTR_NAME,
    attr.ATTR_VALUE
  FROM KSOR_ORG_TYPE_ATTR attr
  WHERE NOT EXISTS(SELECT
                     'X'
                   FROM KSEN_TYPE_ATTR attrInner
                   WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_ATTR
INSERT INTO KSEN_ORG_ATTR
(ID, OBJ_ID, ATTR_KEY, ATTR_VALUE, OWNER_ID)
  SELECT
    ID,
    OBJ_ID,
    ATTR_NAME,
    ATTR_VALUE,
    OWNER
  FROM KSOR_ORG_ATTR
/

--KSEN_ORG_ORG_RELTN
INSERT INTO KSEN_ORG_ORG_RELTN
(ID, OBJ_ID, ORG_RELTN_TYPE, ORG_RELTN_STATE, ORG_ID,
 RELATED_ORG_ID, EXPIR_DT, EFF_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID)
  SELECT
    ID,
    OBJ_ID,
    TYPE,
    COALESCE(ST, 'ACTIVE'),
    ORG,
    RELATED_ORG,
    EXPIR_DT,
    EFF_DT,
    VER_NBR,
    COALESCE(CREATETIME, SYSDATE),
    COALESCE(CREATEID, 'SYSTEMLOADER'),
    UPDATETIME,
    UPDATEID
  FROM KSOR_ORG_ORG_RELTN  oor
  WHERE oor.RELATED_ORG IS NOT null AND oor.ORG IS NOT null
/

--Move types from custom org org relation type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
  SELECT
    TYPE_KEY,
    NAME,
    TYPE_DESC,
    'http://student.kuali.org/wsdl/organization/OrgOrgRelationInfo',
    'http://student.kuali.org/wsdl/organization/OrganizationService',
    EFF_DT,
    EXPIR_DT,
    VER_NBR,
    'SYSTEMLOADER',
    TO_DATE('20130731', 'YYYYMMDD')
  FROM KSOR_ORG_ORG_RELTN_TYPE
  WHERE TYPE_KEY NOT IN (SELECT
                           TYPE_KEY
                         FROM KSEN_TYPE)
/

--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
  SELECT
    SYS_GUID() ID,
    attr.OWNER,
    attr.ATTR_NAME,
    attr.ATTR_VALUE
  FROM KSOR_ORG_ORG_RELTN_TYPE_ATTR attr
  WHERE NOT EXISTS(SELECT
                     'X'
                   FROM KSEN_TYPE_ATTR attrInner
                   WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_ORG_REL_ATTR
INSERT INTO KSEN_ORG_ORG_REL_ATTR
(ID, OBJ_ID, ATTR_KEY, ATTR_VALUE, OWNER_ID)
  SELECT
    ID,
    OBJ_ID,
    ATTR_NAME,
    ATTR_VALUE,
    OWNER
  FROM KSOR_ORG_ORG_RELTN_ATTR
/

--KSEN_ORG_HIRCHY
INSERT INTO KSEN_ORG_HIRCHY
(ID, OBJ_ID, ORG_HIRCHY_TYPE, ORG_HIRCHY_STATE, NAME, DESCR_PLAIN, ROOT_ORG_ID, EXPIR_DT, EFF_DT, VER_NBR, CREATETIME, CREATEID)
  SELECT
    ID,
    OBJ_ID,
    ID,
    'kuali.org.hierarchy.state.active',
    NAME,
    DESCR,
    ROOT_ORG,
    EXPIR_DT,
    EFF_DT,
    VER_NBR,
    TO_DATE('20130731', 'YYYYMMDD'),
    'SYSTEMLOADER'
  FROM KSOR_ORG_HIRCHY
/

--insert org hierarchy type
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
  SELECT
    ORG_HIRCHY_TYPE,
    NAME,
    'http://student.kuali.org/wsdl/organization/OrgHierarchyInfo',
    'http://student.kuali.org/wsdl/organization/OrganizationService',
    EFF_DT,
    EXPIR_DT,
    1,
    'SYSTEMLOADER',
    TO_DATE('20130731', 'YYYYMMDD')
  FROM KSEN_ORG_HIRCHY
  WHERE ORG_HIRCHY_TYPE NOT IN (SELECT
                                  TYPE_KEY
                                FROM KSEN_TYPE)
/

--KSEN_ORG_HIRCHY_ATTR
INSERT INTO KSEN_ORG_HIRCHY_ATTR
(ID, OBJ_ID, ATTR_KEY, ATTR_VALUE, OWNER_ID)
  SELECT
    ID,
    OBJ_ID,
    ATTR_NAME,
    ATTR_VALUE,
    OWNER
  FROM KSOR_ORG_HIRCHY_ATTR
/

--INSERT INTO KSEN_ORG_HIRCHY_OORT
INSERT INTO KSEN_ORG_HIRCHY_OORT
(ORG_HIRCHY_ID, ORG_ORG_RELTN_TYPE_ID)
  SELECT
    DISTINCT ORG_HIRCHY_ID,
    OOR_TYPE
  FROM (SELECT
          DISTINCT ORG.ORG_TYPE,
          oor.ORG_RELTN_TYPE OOR_TYPE
        FROM KSEN_ORG ORG, KSEN_ORG_ORG_RELTN OOR
        WHERE (OOR.ORG_ID = ORG.ID OR OOR.RELATED_ORG_ID = ORG.ID)) TABLE1
    INNER JOIN
    (SELECT
       *
     FROM KSOR_ORG_HIRCHY_JN_ORG_TYPE) TABLE2
      ON TABLE1.ORG_TYPE = TABLE2.ORG_TYPE_ID
/

--KSEN_ORG_PERS_RELTN
INSERT INTO KSEN_ORG_PERS_RELTN
(ID, OBJ_ID, ORG_PERS_RELTN_TYPE, ORG_PERS_RELTN_STATE, ORG_ID, PERS_ID, EXPIR_DT, EFF_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID)
  SELECT
    ID,
    OBJ_ID,
    ORG_PERS_RELTN_TYPE,
    COALESCE(ST, 'ACTIVE'),
    ORG,
    PERS_ID,
    EXPIR_DT,
    EFF_DT,
    VER_NBR,
    COALESCE(CREATETIME, SYSDATE),
    COALESCE(CREATEID, 'SYSTEMLOADER'),
    UPDATETIME,
    UPDATEID
  FROM KSOR_ORG_PERS_RELTN
/

--Move types from custom org person relation type table into the standard type table.
INSERT INTO KSEN_TYPE
(TYPE_KEY, NAME, DESCR_PLAIN, REF_OBJECT_URI, SERVICE_URI, EFF_DT, EXPIR_DT, VER_NBR, CREATEID, CREATETIME)
  SELECT
    TYPE_KEY,
    NAME,
    TYPE_DESC,
    'http://student.kuali.org/wsdl/organization/OrgPersonRelationInfo',
    'http://student.kuali.org/wsdl/organization/OrganizationService',
    EFF_DT,
    EXPIR_DT,
    VER_NBR,
    'SYSTEMLOADER',
    TO_DATE('20130731', 'YYYYMMDD')
  FROM KSOR_ORG_PERS_RELTN_TYPE
  WHERE TYPE_KEY NOT IN (SELECT
                           TYPE_KEY
                         FROM KSEN_TYPE)
/

--Move type attrs from custom table into the standard type attr table.
INSERT INTO KSEN_TYPE_ATTR
(ID, OWNER_ID, ATTR_KEY, ATTR_VALUE)
  SELECT
    SYS_GUID() ID,
    attr.OWNER,
    attr.ATTR_NAME,
    attr.ATTR_VALUE
  FROM KSOR_ORG_PERS_RELTN_TYPE_ATTR attr
  WHERE NOT EXISTS(SELECT
                     'X'
                   FROM KSEN_TYPE_ATTR attrInner
                   WHERE attr.OWNER = attrInner.OWNER_ID AND attr.ATTR_NAME = attrInner.ATTR_KEY)
/

--KSEN_ORG_PERS_REL_ATTR
INSERT INTO KSEN_ORG_PERS_REL_ATTR
(ID, OBJ_ID, ATTR_KEY, ATTR_VALUE, OWNER_ID)
  SELECT
    ID,
    OBJ_ID,
    ATTR_NAME,
    ATTR_VALUE,
    OWNER
  FROM KSOR_ORG_PERS_RELTN_ATTR
/

--KSEN_ORG_POS_RESTR
INSERT INTO KSEN_ORG_POS_RESTR
(ID, OBJ_ID, ORG_ID, TITLE, DESCR_PLAIN, STD_DUR_TYPE, STD_DUR_TIME_QTY, MIN_NUM_REL, MAX_NUM_REL, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID, ORG_PERS_RELTN_TYPE)
  SELECT
    ID,
    OBJ_ID,
    ORG,
    TTL,
    DESCR,
    ATP_DUR_TYP_KEY,
    TM_QUANTITY,
    MIN_NUM_RELTN,
    MAX_NUM_RELTN,
    VER_NBR,
    CREATETIME,
    CREATEID,
    UPDATETIME,
    UPDATEID,
    PERS_RELTN_TYPE
  FROM KSOR_ORG_POS_RESTR
/

--KSEN_ORG_POS_RESTR
INSERT INTO KSEN_ORG_POS_RESTR_ATTR
(ID, OBJ_ID, ATTR_KEY, ATTR_VALUE, OWNER_ID)
  SELECT
    ID,
    OBJ_ID,
    ATTR_NAME,
    ATTR_VALUE,
    OWNER
  FROM KSOR_ORG_POS_RESTR_ATTR
/

--DROP TABLES
DROP TABLE KSOR_ORG_JN_ORG_PERS_REL_TYPE CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_HIRCHY_JN_ORG_TYPE CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_TYPE_JN_ORG_PERRL_TYP CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_ORG_RELTN_TYPE_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_ORG_RELTN_TYPE CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_PERS_RELTN_TYPE_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_PERS_RELTN_TYPE CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_POS_RESTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_POS_RESTR_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_PERS_RELTN CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_PERS_RELTN_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_ORG_RELTN CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_ORG_RELTN_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_HIRCHY CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_HIRCHY_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_TYPE_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_TYPE CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG_ATTR CASCADE CONSTRAINTS PURGE
/
DROP TABLE KSOR_ORG CASCADE CONSTRAINTS PURGE
/
