
CREATE  INDEX KSEN_ORG_I1 ON KSEN_ORG
(ORG_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_ATTR_IF1 ON KSEN_ORG_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_ORG_CD_I1 ON KSEN_ORG_CD
(ORG_CD_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_CD_IF1 ON KSEN_ORG_CD
(ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_CD_ATTR_IF1 ON KSEN_ORG_CD_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_ORG_HIRCHY_I1 ON KSEN_ORG_HIRCHY
(ORG_HIRCHY_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_HIRCHY_IF1 ON KSEN_ORG_HIRCHY
(ROOT_ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_HIRCHY_ATTR_IF1 ON KSEN_ORG_HIRCHY_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_ORG_HIRCHY_OORT_IF1 ON KSEN_ORG_HIRCHY_OORT
(ORG_HIRCHY_ID   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_REL_ATTR_IF1 ON KSEN_ORG_ORG_REL_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_RELTN_I1 ON KSEN_ORG_ORG_RELTN
(ORG_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_RELTN_I2 ON KSEN_ORG_ORG_RELTN
(ORG_ID   ASC,ORG_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_RELTN_I3 ON KSEN_ORG_ORG_RELTN
(RELATED_ORG_ID   ASC,ORG_RELTN_TYPE   ASC,ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_RELTN_IF1 ON KSEN_ORG_ORG_RELTN
(ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_ORG_RELTN_IF2 ON KSEN_ORG_ORG_RELTN
(RELATED_ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_REL_ATTR_IF1 ON KSEN_ORG_PERS_REL_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_RELTN_I1 ON KSEN_ORG_PERS_RELTN
(ORG_PERS_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_RELTN_I2 ON KSEN_ORG_PERS_RELTN
(ORG_ID   ASC,ORG_PERS_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_RELTN_I3 ON KSEN_ORG_PERS_RELTN
(PERS_ID   ASC,ORG_PERS_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_RELTN_I4 ON KSEN_ORG_PERS_RELTN
(ORG_ID   ASC,PERS_ID   ASC,ORG_PERS_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_PERS_RELTN_IF1 ON KSEN_ORG_PERS_RELTN
(ORG_ID   ASC)
/


CREATE  INDEX KSEN_ORG_POS_RESTR_IF2 ON KSEN_ORG_POS_RESTR
(ORG_ID   ASC)
/


CREATE  INDEX kSEN_ORG_POS_RESTR_I1 ON KSEN_ORG_POS_RESTR
(ORG_PERS_RELTN_TYPE   ASC)
/


CREATE  INDEX KSEN_ORG_POS_RESTR_ATTR_IF1 ON KSEN_ORG_POS_RESTR_ATTR
(OWNER_ID   ASC)
/


ALTER TABLE KSEN_ORG_ATTR
	ADD (CONSTRAINT KSEN_ORG_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_CD
	ADD (CONSTRAINT KSEN_ORG_CD_FK1 FOREIGN KEY (ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_CD_ATTR
	ADD (CONSTRAINT KSEN_ORG_CD_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG_CD (ID))
/


ALTER TABLE KSEN_ORG_HIRCHY
	ADD (CONSTRAINT KSEN_ORG_HIRCHY_FK1 FOREIGN KEY (ROOT_ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_HIRCHY_ATTR
	ADD (CONSTRAINT KSEN_ORG_HIRCHY_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG_HIRCHY (ID))
/


ALTER TABLE KSEN_ORG_HIRCHY_OORT
	ADD (CONSTRAINT KSEN_ORG_HIRCHY_OORT FOREIGN KEY (ORG_HIRCHY_ID) REFERENCES KSEN_ORG_HIRCHY (ID))
/


ALTER TABLE KSEN_ORG_ORG_REL_ATTR
	ADD (CONSTRAINT KSEN_ORG_REL_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG_ORG_RELTN (ID))
/


ALTER TABLE KSEN_ORG_ORG_RELTN
	ADD (CONSTRAINT KSEN_ORG_ORG_RELTN_FK1 FOREIGN KEY (ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_ORG_RELTN
	ADD (CONSTRAINT KSEN_ORG_ORG_RELTN_FK2 FOREIGN KEY (RELATED_ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_PERS_REL_ATTR
	ADD (CONSTRAINT KSEN_ORG_PERS_REL_ATTR_IF1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG_PERS_RELTN (ID))
/


ALTER TABLE KSEN_ORG_PERS_RELTN
	ADD (CONSTRAINT KSEN_ORG_PERS_RELTN_FK1 FOREIGN KEY (ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_POS_RESTR
	ADD (CONSTRAINT KSEN_ORG_POS_RESTR_FK2 FOREIGN KEY (ORG_ID) REFERENCES KSEN_ORG (ID))
/


ALTER TABLE KSEN_ORG_POS_RESTR_ATTR
	ADD (CONSTRAINT KSEN_ORG_POS_RESTR_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ORG_POS_RESTR (ID))
/
