
DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_TYPE             VARCHAR2(255) NOT NULL ,
	ORG_STATE            VARCHAR2(255) NOT NULL ,
	LONG_NAME            VARCHAR2(255) NOT NULL ,
	LONG_DESCR_PLAIN     VARCHAR2(4000) NULL ,
	LONG_DESCR_FORMATTED VARCHAR2(4000) NULL ,
	SHORT_NAME           VARCHAR2(255) NULL ,
	SORT_NAME            VARCHAR2(255) NULL ,
	SHORT_DESCR_PLAIN    VARCHAR2(4000) NULL ,
	SHORT_DESCR_FORMATTED VARCHAR2(4000) NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG
	ADD CONSTRAINT  KSEN_ORG_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_ATTR
	ADD CONSTRAINT  KSEN_ORG_ATTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_CD';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_CD CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_CD
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_CD_TYPE          VARCHAR2(255) NOT NULL ,
	ORG_CD_STATE         VARCHAR2(255) NOT NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	VALUE                VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_CD
	ADD CONSTRAINT  KSEN_ORG_CD_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_CD_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_CD_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_CD_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_CD_ATTR
	ADD CONSTRAINT  KSEN_ORG_CD_ATTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_HIRCHY';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_HIRCHY CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_HIRCHY
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_HIRCHY_TYPE      VARCHAR2(255) NOT NULL ,
	ORG_HIRCHY_STATE     VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(255) NULL ,
	ROOT_ORG_ID          VARCHAR2(255) NULL ,	
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_HIRCHY
	ADD CONSTRAINT  KSEN_ORG_HIRCHY_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_HIRCHY_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_HIRCHY_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_HIRCHY_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_HIRCHY_ATTR
	ADD CONSTRAINT  KSEN_ORG_HIRCHY_ATTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_HIRCHY_OORT';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_HIRCHY_OORT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_HIRCHY_OORT
(
	ORG_HIRCHY_ID        VARCHAR2(255) NOT NULL ,
	ORG_ORG_RELTN_TYPE_ID VARCHAR2(255) NOT NULL 
)
/


ALTER TABLE KSEN_ORG_HIRCHY_OORT
	ADD CONSTRAINT  KSEN_ORG_HIRCHY_OORT_P PRIMARY KEY (ORG_HIRCHY_ID,ORG_ORG_RELTN_TYPE_ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_ORG_REL_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_ORG_REL_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_ORG_REL_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_ORG_REL_ATTR
	ADD CONSTRAINT  KSEN_ORG_ORG_REL_ATTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_ORG_RELTN';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_ORG_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_ORG_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_RELTN_TYPE       VARCHAR2(255) NOT NULL ,
	ORG_RELTN_STATE      VARCHAR2(255) NOT NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	RELATED_ORG_ID       VARCHAR2(255) NOT NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,	
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/


ALTER TABLE KSEN_ORG_ORG_RELTN
	ADD CONSTRAINT  KSEN_ORG_ORG_RELTN_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_PERS_REL_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_PERS_REL_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_PERS_REL_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL
)
/


ALTER TABLE KSEN_ORG_PERS_REL_ATTR
	ADD CONSTRAINT  KSEN_ORG_PERS_REL_ATTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_PERS_RELTN';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_PERS_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_PERS_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_PERS_RELTN_TYPE  VARCHAR2(255) NOT NULL ,
	ORG_PERS_RELTN_STATE VARCHAR2(255) NOT NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	PERS_ID              VARCHAR2(255) NOT NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL
)
/


ALTER TABLE KSEN_ORG_PERS_RELTN
	ADD CONSTRAINT  KSEN_ORG_PERS_RELTN_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_POS_RESTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_POS_RESTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_POS_RESTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	TITLE                VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	STD_DUR_TYPE         VARCHAR2(255) NULL ,
	STD_DUR_TIME_QTY     NUMBER NULL ,
	MIN_NUM_REL          NUMBER NULL ,
	MAX_NUM_REL          NUMBER NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	ORG_PERS_RELTN_TYPE  VARCHAR2(255) NOT NULL
)
/


ALTER TABLE KSEN_ORG_POS_RESTR
	ADD CONSTRAINT  KSEN_ORG_POS_RESTR_P PRIMARY KEY (ID)
/


DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_ORG_POS_RESTR_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ORG_POS_RESTR_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_ORG_POS_RESTR_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL
)
/


ALTER TABLE KSEN_ORG_POS_RESTR_ATTR
	ADD CONSTRAINT  KSEN_ORG_POS_RESTR_ATTR_P PRIMARY KEY (ID)
/
