
package org.collegeboard.inas._2013;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NeedAnalysisXmlEngine", targetNamespace = "http://INAS.collegeboard.org/2013/", wsdlLocation = "file:/home/mike/workspace/bsinas/src/main/resources/wsdl/bsinas_2013.wsdl")
public class NeedAnalysisXmlEngine
    extends Service
{

    private final static URL NEEDANALYSISXMLENGINE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.collegeboard.inas._2013.NeedAnalysisXmlEngine.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.collegeboard.inas._2013.NeedAnalysisXmlEngine.class.getResource(".");
            url = new URL(baseUrl, "file:/home/mike/workspace/bsinas/src/main/resources/wsdl/bsinas_2013.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/mike/workspace/bsinas/src/main/resources/wsdl/bsinas_2013.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NEEDANALYSISXMLENGINE_WSDL_LOCATION = url;
    }

    public NeedAnalysisXmlEngine(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NeedAnalysisXmlEngine() {
        super(NEEDANALYSISXMLENGINE_WSDL_LOCATION, new QName("http://INAS.collegeboard.org/2013/", "NeedAnalysisXmlEngine"));
    }

    /**
     * 
     * @return
     *     returns INeedAnalysisXmlEngine
     */
    @WebEndpoint(name = "basicHttp")
    public INeedAnalysisXmlEngine getBasicHttp() {
        return super.getPort(new QName("http://INAS.collegeboard.org/2013/", "basicHttp"), INeedAnalysisXmlEngine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INeedAnalysisXmlEngine
     */
    @WebEndpoint(name = "basicHttp")
    public INeedAnalysisXmlEngine getBasicHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://INAS.collegeboard.org/2013/", "basicHttp"), INeedAnalysisXmlEngine.class, features);
    }

}
