//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.26 at 09:57:35 AM MDT 
//


package com.sigmasys.kuali.ksa.transform;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account-status-type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="is-kim-account" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="can-authenticate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}person-name" minOccurs="0"/>
 *         &lt;element ref="{}postal-address" minOccurs="0"/>
 *         &lt;element ref="{}electronic-contact" minOccurs="0"/>
 *         &lt;element name="credit-limit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountStatusType",
    "identifier",
    "isKimAccount",
    "canAuthenticate",
    "personName",
    "postalAddress",
    "electronicContact",
    "creditLimit"
})
@XmlRootElement(name = "account")
public class Account {

    @XmlElement(name = "account-status-type")
    protected Object accountStatusType;
    @XmlElement(required = true)
    protected Object identifier;
    @XmlElement(name = "is-kim-account", required = true)
    protected Object isKimAccount;
    @XmlElement(name = "can-authenticate")
    protected Object canAuthenticate;
    @XmlElement(name = "person-name")
    protected PersonName personName;
    @XmlElement(name = "postal-address")
    protected PostalAddress postalAddress;
    @XmlElement(name = "electronic-contact")
    protected ElectronicContact electronicContact;
    @XmlElement(name = "credit-limit")
    protected BigDecimal creditLimit;

    /**
     * Gets the value of the accountStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAccountStatusType() {
        return accountStatusType;
    }

    /**
     * Sets the value of the accountStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAccountStatusType(Object value) {
        this.accountStatusType = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdentifier(Object value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the isKimAccount property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIsKimAccount() {
        return isKimAccount;
    }

    /**
     * Sets the value of the isKimAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIsKimAccount(Object value) {
        this.isKimAccount = value;
    }

    /**
     * Gets the value of the canAuthenticate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCanAuthenticate() {
        return canAuthenticate;
    }

    /**
     * Sets the value of the canAuthenticate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCanAuthenticate(Object value) {
        this.canAuthenticate = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setPersonName(PersonName value) {
        this.personName = value;
    }

    /**
     * Gets the value of the postalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PostalAddress }
     *     
     */
    public PostalAddress getPostalAddress() {
        return postalAddress;
    }

    /**
     * Sets the value of the postalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalAddress }
     *     
     */
    public void setPostalAddress(PostalAddress value) {
        this.postalAddress = value;
    }

    /**
     * Gets the value of the electronicContact property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicContact }
     *     
     */
    public ElectronicContact getElectronicContact() {
        return electronicContact;
    }

    /**
     * Sets the value of the electronicContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicContact }
     *     
     */
    public void setElectronicContact(ElectronicContact value) {
        this.electronicContact = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditLimit(BigDecimal value) {
        this.creditLimit = value;
    }

}
