//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 09:08:39 PM GMT-05:00 
//


package com.sigmasys.kuali.ksa.transform;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sigmasys.kuali.ksa.transform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sigmasys.kuali.ksa.transform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KsaBatchTransactionResponse }
     * 
     */
    public KsaBatchTransactionResponse createKsaBatchTransactionResponse() {
        return new KsaBatchTransactionResponse();
    }

    /**
     * Create an instance of {@link TransactionList }
     * 
     */
    public TransactionList createTransactionList() {
        return new TransactionList();
    }

    /**
     * Create an instance of {@link Receipt }
     * 
     */
    public Receipt createReceipt() {
        return new Receipt();
    }

    /**
     * Create an instance of {@link ElectronicContact }
     * 
     */
    public ElectronicContact createElectronicContact() {
        return new ElectronicContact();
    }

    /**
     * Create an instance of {@link GeneralLedgerReport }
     * 
     */
    public GeneralLedgerReport createGeneralLedgerReport() {
        return new GeneralLedgerReport();
    }

    /**
     * Create an instance of {@link FailedTransactionsReport }
     * 
     */
    public FailedTransactionsReport createFailedTransactionsReport() {
        return new FailedTransactionsReport();
    }

    /**
     * Create an instance of {@link AgedBalanceReport }
     * 
     */
    public AgedBalanceReport createAgedBalanceReport() {
        return new AgedBalanceReport();
    }

    /**
     * Create an instance of {@link AccountReport }
     * 
     */
    public AccountReport createAccountReport() {
        return new AccountReport();
    }

    /**
     * Create an instance of {@link ExternalStatementRemove }
     * 
     */
    public ExternalStatementRemove createExternalStatementRemove() {
        return new ExternalStatementRemove();
    }

    /**
     * Create an instance of {@link BatchCheck }
     * 
     */
    public BatchCheck createBatchCheck() {
        return new BatchCheck();
    }

    /**
     * Create an instance of {@link BatchAch }
     * 
     */
    public BatchAch createBatchAch() {
        return new BatchAch();
    }

    /**
     * Create an instance of {@link BatchAccountResponse }
     * 
     */
    public BatchAccountResponse createBatchAccountResponse() {
        return new BatchAccountResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link KsaBill }
     * 
     */
    public KsaBill createKsaBill() {
        return new KsaBill();
    }

    /**
     * Create an instance of {@link BatchAccount }
     * 
     */
    public BatchAccount createBatchAccount() {
        return new BatchAccount();
    }

    /**
     * Create an instance of {@link Irs1098T }
     * 
     */
    public Irs1098T createIrs1098T() {
        return new Irs1098T();
    }

    /**
     * Create an instance of {@link StudentProfile }
     * 
     */
    public StudentProfile createStudentProfile() {
        return new StudentProfile();
    }

    /**
     * Create an instance of {@link KsaTransaction }
     * 
     */
    public KsaTransaction createKsaTransaction() {
        return new KsaTransaction();
    }

    /**
     * Create an instance of {@link KsaBatchTransaction }
     * 
     */
    public KsaBatchTransaction createKsaBatchTransaction() {
        return new KsaBatchTransaction();
    }

    /**
     * Create an instance of {@link ExternalStatementBatchResponse }
     * 
     */
    public ExternalStatementBatchResponse createExternalStatementBatchResponse() {
        return new ExternalStatementBatchResponse();
    }

    /**
     * Create an instance of {@link KsaTransaction.Override }
     * 
     */
    public KsaTransaction.Override createKsaTransactionOverride() {
        return new KsaTransaction.Override();
    }

    /**
     * Create an instance of {@link StudentProfile.PeriodInformation }
     * 
     */
    public StudentProfile.PeriodInformation createStudentProfilePeriodInformation() {
        return new StudentProfile.PeriodInformation();
    }

    /**
     * Create an instance of {@link StudentProfile.StudentInformation }
     * 
     */
    public StudentProfile.StudentInformation createStudentProfileStudentInformation() {
        return new StudentProfile.StudentInformation();
    }

    /**
     * Create an instance of {@link KsaBill.Balances }
     * 
     */
    public KsaBill.Balances createKsaBillBalances() {
        return new KsaBill.Balances();
    }

    /**
     * Create an instance of {@link KsaBill.Balances.WithoutDeferments }
     * 
     */
    public KsaBill.Balances.WithoutDeferments createKsaBillBalancesWithoutDeferments() {
        return new KsaBill.Balances.WithoutDeferments();
    }

    /**
     * Create an instance of {@link KsaBill.Balances.WithDeferments }
     * 
     */
    public KsaBill.Balances.WithDeferments createKsaBillBalancesWithDeferments() {
        return new KsaBill.Balances.WithDeferments();
    }

    /**
     * Create an instance of {@link Account.ProtectedInformation }
     * 
     */
    public Account.ProtectedInformation createAccountProtectedInformation() {
        return new Account.ProtectedInformation();
    }

    /**
     * Create an instance of {@link AccountReport.Balances }
     * 
     */
    public AccountReport.Balances createAccountReportBalances() {
        return new AccountReport.Balances();
    }

    /**
     * Create an instance of {@link AgedBalanceReport.AgedAccountDetail }
     * 
     */
    public AgedBalanceReport.AgedAccountDetail createAgedBalanceReportAgedAccountDetail() {
        return new AgedBalanceReport.AgedAccountDetail();
    }

    /**
     * Create an instance of {@link FailedTransactionsReport.FailureGroup }
     * 
     */
    public FailedTransactionsReport.FailureGroup createFailedTransactionsReportFailureGroup() {
        return new FailedTransactionsReport.FailureGroup();
    }

    /**
     * Create an instance of {@link KsaBatchTransactionResponse.Accepted }
     * 
     */
    public KsaBatchTransactionResponse.Accepted createKsaBatchTransactionResponseAccepted() {
        return new KsaBatchTransactionResponse.Accepted();
    }

    /**
     * Create an instance of {@link KsaBatchTransactionResponse.Failed }
     * 
     */
    public KsaBatchTransactionResponse.Failed createKsaBatchTransactionResponseFailed() {
        return new KsaBatchTransactionResponse.Failed();
    }

    /**
     * Create an instance of {@link KsaBatchTransactionResponse.BatchSummary }
     * 
     */
    public KsaBatchTransactionResponse.BatchSummary createKsaBatchTransactionResponseBatchSummary() {
        return new KsaBatchTransactionResponse.BatchSummary();
    }

    /**
     * Create an instance of {@link LearningUnit }
     * 
     */
    public LearningUnit createLearningUnit() {
        return new LearningUnit();
    }

    /**
     * Create an instance of {@link KeyPair }
     * 
     */
    public KeyPair createKeyPair() {
        return new KeyPair();
    }

    /**
     * Create an instance of {@link ListTransaction }
     * 
     */
    public ListTransaction createListTransaction() {
        return new ListTransaction();
    }

    /**
     * Create an instance of {@link TransactionList.Rollup }
     * 
     */
    public TransactionList.Rollup createTransactionListRollup() {
        return new TransactionList.Rollup();
    }

    /**
     * Create an instance of {@link Receipt.ForeignTransaction }
     * 
     */
    public Receipt.ForeignTransaction createReceiptForeignTransaction() {
        return new Receipt.ForeignTransaction();
    }

    /**
     * Create an instance of {@link Receipt.TransactionType }
     * 
     */
    public Receipt.TransactionType createReceiptTransactionType() {
        return new Receipt.TransactionType();
    }

    /**
     * Create an instance of {@link ElectronicContact.TelephoneNumber }
     * 
     */
    public ElectronicContact.TelephoneNumber createElectronicContactTelephoneNumber() {
        return new ElectronicContact.TelephoneNumber();
    }

    /**
     * Create an instance of {@link GeneralLedgerReport.ReportingPeriod }
     * 
     */
    public GeneralLedgerReport.ReportingPeriod createGeneralLedgerReportReportingPeriod() {
        return new GeneralLedgerReport.ReportingPeriod();
    }

    /**
     * Create an instance of {@link GeneralLedgerReport.GeneralLedgerReportEntry }
     * 
     */
    public GeneralLedgerReport.GeneralLedgerReportEntry createGeneralLedgerReportGeneralLedgerReportEntry() {
        return new GeneralLedgerReport.GeneralLedgerReportEntry();
    }

    /**
     * Create an instance of {@link RequestFailure }
     * 
     */
    public RequestFailure createRequestFailure() {
        return new RequestFailure();
    }

    /**
     * Create an instance of {@link AgedBalanceReport.AgeBreakdown }
     * 
     */
    public AgedBalanceReport.AgeBreakdown createAgedBalanceReportAgeBreakdown() {
        return new AgedBalanceReport.AgeBreakdown();
    }

    /**
     * Create an instance of {@link AccountReport.ReportingPeriod }
     * 
     */
    public AccountReport.ReportingPeriod createAccountReportReportingPeriod() {
        return new AccountReport.ReportingPeriod();
    }

    /**
     * Create an instance of {@link AccountReport.Name }
     * 
     */
    public AccountReport.Name createAccountReportName() {
        return new AccountReport.Name();
    }

    /**
     * Create an instance of {@link AccountReport.TransactionDetail }
     * 
     */
    public AccountReport.TransactionDetail createAccountReportTransactionDetail() {
        return new AccountReport.TransactionDetail();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link ExternalStatement }
     * 
     */
    public ExternalStatement createExternalStatement() {
        return new ExternalStatement();
    }

    /**
     * Create an instance of {@link ExternalStatementRemoveResponse }
     * 
     */
    public ExternalStatementRemoveResponse createExternalStatementRemoveResponse() {
        return new ExternalStatementRemoveResponse();
    }

    /**
     * Create an instance of {@link ExternalStatementRemove.ByAccountIdentifier }
     * 
     */
    public ExternalStatementRemove.ByAccountIdentifier createExternalStatementRemoveByAccountIdentifier() {
        return new ExternalStatementRemove.ByAccountIdentifier();
    }

    /**
     * Create an instance of {@link ExternalStatementRemove.ByDate }
     * 
     */
    public ExternalStatementRemove.ByDate createExternalStatementRemoveByDate() {
        return new ExternalStatementRemove.ByDate();
    }

    /**
     * Create an instance of {@link ExternalStatementRemove.ByUniqueKey }
     * 
     */
    public ExternalStatementRemove.ByUniqueKey createExternalStatementRemoveByUniqueKey() {
        return new ExternalStatementRemove.ByUniqueKey();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link BatchCheck.BatchControl }
     * 
     */
    public BatchCheck.BatchControl createBatchCheckBatchControl() {
        return new BatchCheck.BatchControl();
    }

    /**
     * Create an instance of {@link Ach }
     * 
     */
    public Ach createAch() {
        return new Ach();
    }

    /**
     * Create an instance of {@link BatchAch.BatchControl }
     * 
     */
    public BatchAch.BatchControl createBatchAchBatchControl() {
        return new BatchAch.BatchControl();
    }

    /**
     * Create an instance of {@link BatchAccountResponse.Accepted }
     * 
     */
    public BatchAccountResponse.Accepted createBatchAccountResponseAccepted() {
        return new BatchAccountResponse.Accepted();
    }

    /**
     * Create an instance of {@link BatchAccountResponse.Rejected }
     * 
     */
    public BatchAccountResponse.Rejected createBatchAccountResponseRejected() {
        return new BatchAccountResponse.Rejected();
    }

    /**
     * Create an instance of {@link BatchAccountResponse.BatchSummary }
     * 
     */
    public BatchAccountResponse.BatchSummary createBatchAccountResponseBatchSummary() {
        return new BatchAccountResponse.BatchSummary();
    }

    /**
     * Create an instance of {@link ExternalStatementResponse }
     * 
     */
    public ExternalStatementResponse createExternalStatementResponse() {
        return new ExternalStatementResponse();
    }

    /**
     * Create an instance of {@link ExternalStatementBatch }
     * 
     */
    public ExternalStatementBatch createExternalStatementBatch() {
        return new ExternalStatementBatch();
    }

    /**
     * Create an instance of {@link MailingData }
     * 
     */
    public MailingData createMailingData() {
        return new MailingData();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link KsaBill.Cycle }
     * 
     */
    public KsaBill.Cycle createKsaBillCycle() {
        return new KsaBill.Cycle();
    }

    /**
     * Create an instance of {@link KsaBill.AccountOwner }
     * 
     */
    public KsaBill.AccountOwner createKsaBillAccountOwner() {
        return new KsaBill.AccountOwner();
    }

    /**
     * Create an instance of {@link KsaBill.BillAddressedTo }
     * 
     */
    public KsaBill.BillAddressedTo createKsaBillBillAddressedTo() {
        return new KsaBill.BillAddressedTo();
    }

    /**
     * Create an instance of {@link BatchAccount.BatchControl }
     * 
     */
    public BatchAccount.BatchControl createBatchAccountBatchControl() {
        return new BatchAccount.BatchControl();
    }

    /**
     * Create an instance of {@link Irs1098T.FormCheckboxes }
     * 
     */
    public Irs1098T.FormCheckboxes createIrs1098TFormCheckboxes() {
        return new Irs1098T.FormCheckboxes();
    }

    /**
     * Create an instance of {@link Irs1098T.Filer }
     * 
     */
    public Irs1098T.Filer createIrs1098TFiler() {
        return new Irs1098T.Filer();
    }

    /**
     * Create an instance of {@link Irs1098T.Student }
     * 
     */
    public Irs1098T.Student createIrs1098TStudent() {
        return new Irs1098T.Student();
    }

    /**
     * Create an instance of {@link Irs1098T.Financial }
     * 
     */
    public Irs1098T.Financial createIrs1098TFinancial() {
        return new Irs1098T.Financial();
    }

    /**
     * Create an instance of {@link KsaTransaction.Document }
     * 
     */
    public KsaTransaction.Document createKsaTransactionDocument() {
        return new KsaTransaction.Document();
    }

    /**
     * Create an instance of {@link KsaBatchTransaction.BatchControl }
     * 
     */
    public KsaBatchTransaction.BatchControl createKsaBatchTransactionBatchControl() {
        return new KsaBatchTransaction.BatchControl();
    }

    /**
     * Create an instance of {@link ExternalStatementBatchResponse.Statement }
     * 
     */
    public ExternalStatementBatchResponse.Statement createExternalStatementBatchResponseStatement() {
        return new ExternalStatementBatchResponse.Statement();
    }

    /**
     * Create an instance of {@link ExternalStatementBatchResponse.StatementRemove }
     * 
     */
    public ExternalStatementBatchResponse.StatementRemove createExternalStatementBatchResponseStatementRemove() {
        return new ExternalStatementBatchResponse.StatementRemove();
    }

    /**
     * Create an instance of {@link KsaTransaction.Override.GeneralLedgerOverride }
     * 
     */
    public KsaTransaction.Override.GeneralLedgerOverride createKsaTransactionOverrideGeneralLedgerOverride() {
        return new KsaTransaction.Override.GeneralLedgerOverride();
    }

    /**
     * Create an instance of {@link StudentProfile.PeriodInformation.Study }
     * 
     */
    public StudentProfile.PeriodInformation.Study createStudentProfilePeriodInformationStudy() {
        return new StudentProfile.PeriodInformation.Study();
    }

    /**
     * Create an instance of {@link StudentProfile.StudentInformation.ProgramOfStudy }
     * 
     */
    public StudentProfile.StudentInformation.ProgramOfStudy createStudentProfileStudentInformationProgramOfStudy() {
        return new StudentProfile.StudentInformation.ProgramOfStudy();
    }

    /**
     * Create an instance of {@link KsaBill.Balances.WithoutDeferments.AgedBalance }
     * 
     */
    public KsaBill.Balances.WithoutDeferments.AgedBalance createKsaBillBalancesWithoutDefermentsAgedBalance() {
        return new KsaBill.Balances.WithoutDeferments.AgedBalance();
    }

    /**
     * Create an instance of {@link KsaBill.Balances.WithDeferments.AgedBalance }
     * 
     */
    public KsaBill.Balances.WithDeferments.AgedBalance createKsaBillBalancesWithDefermentsAgedBalance() {
        return new KsaBill.Balances.WithDeferments.AgedBalance();
    }

    /**
     * Create an instance of {@link Account.ProtectedInformation.BankInformation }
     * 
     */
    public Account.ProtectedInformation.BankInformation createAccountProtectedInformationBankInformation() {
        return new Account.ProtectedInformation.BankInformation();
    }

    /**
     * Create an instance of {@link Account.ProtectedInformation.TaxInformation }
     * 
     */
    public Account.ProtectedInformation.TaxInformation createAccountProtectedInformationTaxInformation() {
        return new Account.ProtectedInformation.TaxInformation();
    }

    /**
     * Create an instance of {@link Account.ProtectedInformation.IdentityInformation }
     * 
     */
    public Account.ProtectedInformation.IdentityInformation createAccountProtectedInformationIdentityInformation() {
        return new Account.ProtectedInformation.IdentityInformation();
    }

    /**
     * Create an instance of {@link AccountReport.Balances.AgedBalance }
     * 
     */
    public AccountReport.Balances.AgedBalance createAccountReportBalancesAgedBalance() {
        return new AccountReport.Balances.AgedBalance();
    }

    /**
     * Create an instance of {@link AgedBalanceReport.AgedAccountDetail.AccountBalances }
     * 
     */
    public AgedBalanceReport.AgedAccountDetail.AccountBalances createAgedBalanceReportAgedAccountDetailAccountBalances() {
        return new AgedBalanceReport.AgedAccountDetail.AccountBalances();
    }

    /**
     * Create an instance of {@link FailedTransactionsReport.FailureGroup.Failed }
     * 
     */
    public FailedTransactionsReport.FailureGroup.Failed createFailedTransactionsReportFailureGroupFailed() {
        return new FailedTransactionsReport.FailureGroup.Failed();
    }

    /**
     * Create an instance of {@link FailedTransactionsReport.FailureGroup.BatchRejection }
     * 
     */
    public FailedTransactionsReport.FailureGroup.BatchRejection createFailedTransactionsReportFailureGroupBatchRejection() {
        return new FailedTransactionsReport.FailureGroup.BatchRejection();
    }

    /**
     * Create an instance of {@link KsaBatchTransactionResponse.Accepted.TransactionDetails }
     * 
     */
    public KsaBatchTransactionResponse.Accepted.TransactionDetails createKsaBatchTransactionResponseAcceptedTransactionDetails() {
        return new KsaBatchTransactionResponse.Accepted.TransactionDetails();
    }

}
