//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 09:08:39 PM GMT-05:00 
//


package com.sigmasys.kuali.ksa.transform;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receipt-date" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="receipt-time" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="transaction-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="authorization" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="foreign-transaction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="posted-to-account-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="posting-user-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="transaction-type">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transaction-type-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="transaction-type-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiptDate",
    "receiptTime",
    "transactionIdentifier",
    "authorization",
    "amount",
    "foreignTransaction",
    "postedToAccountIdentifier",
    "postingUserIdentifier",
    "transactionType"
})
@XmlRootElement(name = "receipt")
public class Receipt {

    @XmlElement(name = "receipt-date", required = true)
    protected Object receiptDate;
    @XmlElement(name = "receipt-time", required = true)
    protected Object receiptTime;
    @XmlElement(name = "transaction-identifier", required = true)
    protected Object transactionIdentifier;
    @XmlElement(required = true)
    protected Object authorization;
    @XmlElement(required = true)
    protected Object amount;
    @XmlElement(name = "foreign-transaction")
    protected Receipt.ForeignTransaction foreignTransaction;
    @XmlElement(name = "posted-to-account-identifier", required = true)
    protected Object postedToAccountIdentifier;
    @XmlElement(name = "posting-user-identifier", required = true)
    protected Object postingUserIdentifier;
    @XmlElement(name = "transaction-type", required = true)
    protected Receipt.TransactionType transactionType;

    /**
     * Gets the value of the receiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReceiptDate() {
        return receiptDate;
    }

    /**
     * Sets the value of the receiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReceiptDate(Object value) {
        this.receiptDate = value;
    }

    /**
     * Gets the value of the receiptTime property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReceiptTime() {
        return receiptTime;
    }

    /**
     * Sets the value of the receiptTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReceiptTime(Object value) {
        this.receiptTime = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransactionIdentifier(Object value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the authorization property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAuthorization() {
        return authorization;
    }

    /**
     * Sets the value of the authorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAuthorization(Object value) {
        this.authorization = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAmount(Object value) {
        this.amount = value;
    }

    /**
     * Gets the value of the foreignTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt.ForeignTransaction }
     *     
     */
    public Receipt.ForeignTransaction getForeignTransaction() {
        return foreignTransaction;
    }

    /**
     * Sets the value of the foreignTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt.ForeignTransaction }
     *     
     */
    public void setForeignTransaction(Receipt.ForeignTransaction value) {
        this.foreignTransaction = value;
    }

    /**
     * Gets the value of the postedToAccountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPostedToAccountIdentifier() {
        return postedToAccountIdentifier;
    }

    /**
     * Sets the value of the postedToAccountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPostedToAccountIdentifier(Object value) {
        this.postedToAccountIdentifier = value;
    }

    /**
     * Gets the value of the postingUserIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPostingUserIdentifier() {
        return postingUserIdentifier;
    }

    /**
     * Sets the value of the postingUserIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPostingUserIdentifier(Object value) {
        this.postingUserIdentifier = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt.TransactionType }
     *     
     */
    public Receipt.TransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt.TransactionType }
     *     
     */
    public void setTransactionType(Receipt.TransactionType value) {
        this.transactionType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nativeAmount",
        "currency"
    })
    public static class ForeignTransaction {

        @XmlElement(name = "native-amount", required = true)
        protected BigDecimal nativeAmount;
        @XmlElement(required = true)
        protected String currency;

        /**
         * Gets the value of the nativeAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getNativeAmount() {
            return nativeAmount;
        }

        /**
         * Sets the value of the nativeAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setNativeAmount(BigDecimal value) {
            this.nativeAmount = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transaction-type-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="transaction-type-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionTypeIdentifier",
        "transactionTypeName"
    })
    public static class TransactionType {

        @XmlElement(name = "transaction-type-identifier", required = true)
        protected Object transactionTypeIdentifier;
        @XmlElement(name = "transaction-type-name", required = true)
        protected Object transactionTypeName;

        /**
         * Gets the value of the transactionTypeIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTransactionTypeIdentifier() {
            return transactionTypeIdentifier;
        }

        /**
         * Sets the value of the transactionTypeIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTransactionTypeIdentifier(Object value) {
            this.transactionTypeIdentifier = value;
        }

        /**
         * Gets the value of the transactionTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTransactionTypeName() {
            return transactionTypeName;
        }

        /**
         * Sets the value of the transactionTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTransactionTypeName(Object value) {
            this.transactionTypeName = value;
        }

    }

}
