CREATE USER ksa IDENTIFIED BY ksa123;
CREATE USER rice identified by rice123;


GRANT CREATE SESSION TO ksa;
GRANT CREATE CLUSTER TO ksa;
GRANT CREATE DIMENSION TO ksa;
GRANT CREATE INDEXTYPE TO ksa;
GRANT CREATE JOB TO ksa;
GRANT CREATE MATERIALIZED VIEW TO ksa;
GRANT CREATE OPERATOR TO ksa;
GRANT CREATE PROCEDURE TO ksa;
GRANT CREATE SEQUENCE TO ksa;
GRANT CREATE SNAPSHOT TO ksa;
GRANT CREATE SYNONYM TO ksa;
GRANT CREATE TABLE TO ksa;
GRANT CREATE TRIGGER TO ksa;
GRANT CREATE TYPE TO ksa;
GRANT CREATE VIEW to ksa;
GRANT CREATE ANY TABLE TO ksa;
GRANT CREATE TABLESPACE to ksa;
GRANT UNLIMITED TABLESPACE TO ksa;
COMMIT;


GRANT CREATE SESSION TO rice;
GRANT CREATE CLUSTER TO rice;
GRANT CREATE DIMENSION TO rice;
GRANT CREATE INDEXTYPE TO rice;
GRANT CREATE JOB TO rice;
GRANT CREATE MATERIALIZED VIEW TO rice;
GRANT CREATE OPERATOR TO rice;
GRANT CREATE PROCEDURE TO rice;
GRANT CREATE SEQUENCE TO rice;
GRANT CREATE SNAPSHOT TO rice;
GRANT CREATE SYNONYM TO rice;
GRANT CREATE TABLE TO rice;
GRANT CREATE TRIGGER TO rice;
GRANT CREATE TYPE TO rice;
GRANT CREATE VIEW to rice;
GRANT CREATE ANY TABLE TO rice;
GRANT CREATE TABLESPACE to rice;
GRANT UNLIMITED TABLESPACE TO rice;
COMMIT;