--------------------------------------------------------
--  File created - Wednesday-May-30-2012   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table KSSA_TAG
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_TAG" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	"ACCESS_LEVEL" NUMBER(10,0), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_CREDIT_PERMISSION
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_CREDIT_PERMISSION" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ALLOWABLE_DEBIT_TYPE_MASK" VARCHAR2(20 CHAR), 
	"PRIORITY" NUMBER(10,0), 
	"TRANSACTION_TYPE_ID_FK" VARCHAR2(20 CHAR), 
	"TRANSACTION_TYPE_SUB_CODE_FK" NUMBER(10,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FK1F74048CBC57B259" FOREIGN KEY ("TRANSACTION_TYPE_ID_FK", "TRANSACTION_TYPE_SUB_CODE_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION_TYPE" ("ID", "SUB_CODE") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ACNT_STATUS_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ACNT_STATUS_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_TRANSACTION" 
   (	"TYPE" VARCHAR2(31 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ALLOCATED" NUMBER(19,2), 
	"AMNT" NUMBER(19,2), 
	"EFFECTIVE_DATE" TIMESTAMP (6), 
	"EXTN_ID" VARCHAR2(45 CHAR), 
	"GL_ENTRY_GENERATED" CHAR(1 CHAR), 
	"IS_INTERNAL_TRN" CHAR(1 CHAR), 
	"LEDGER_DATE" TIMESTAMP (6), 
	"LOCKED_ALLOCATED" NUMBER(19,2), 
	"NATIVE_AMNT" NUMBER(19,2), 
	"ORIG_DATE" TIMESTAMP (6), 
	"REFUND_RULE" VARCHAR2(2000 CHAR), 
	"RESP_ENTITY" VARCHAR2(45 CHAR), 
	"STATEMENT_TXT" VARCHAR2(100 CHAR), 
	"IS_REFUNDABLE" CHAR(1 CHAR), 
	"DEFER_ID" NUMBER(19,0), 
	"EXPIRATION_DATE" TIMESTAMP (6), 
	"CLEAR_DATE" TIMESTAMP (6), 
	"IS_DEFERRED" CHAR(1 CHAR), 
	"IS_GL_OVERRIDDEN" CHAR(1 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	"CURRENCY_ID_FK" NUMBER(19,0), 
	"DOCUMENT_ID_FK" NUMBER(19,0), 
	"ROLLUP_ID_FK" NUMBER(19,0), 
	"TRANSACTION_TYPE_ID_FK" VARCHAR2(20 CHAR), 
	"TRANSACTION_TYPE_SUB_CODE_FK" NUMBER(10,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKDCED3DB598518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE, 
	 CONSTRAINT "FKDCED3DB5FB9EC59" FOREIGN KEY ("CURRENCY_ID_FK")
	  REFERENCES "KSA"."KSSA_CURRENCY" ("ID") ENABLE, 
	 CONSTRAINT "FKDCED3DB590ED3EED" FOREIGN KEY ("DOCUMENT_ID_FK")
	  REFERENCES "KSA"."KSSA_DOCUMENT" ("ID") ENABLE, 
	 CONSTRAINT "FKDCED3DB5CE008744" FOREIGN KEY ("TRANSACTION_TYPE_ID_FK", "TRANSACTION_TYPE_SUB_CODE_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION_TYPE" ("ID", "SUB_CODE") ENABLE, 
	 CONSTRAINT "FKDCED3DB5F7D721E7" FOREIGN KEY ("ROLLUP_ID_FK")
	  REFERENCES "KSA"."KSSA_ROLLUP" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_TAX_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_TAX_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_POSTAL_ADDRESS
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_POSTAL_ADDRESS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(10 CHAR), 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"IS_DEFAULT" CHAR(1 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"KIM_ADDRESS_TYPE" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"POSTAL_CODE" VARCHAR2(12 CHAR), 
	"STATE_CODE" VARCHAR2(5 CHAR), 
	"CITY" VARCHAR2(100 CHAR), 
	"LINE1" VARCHAR2(100 CHAR), 
	"LINE2" VARCHAR2(100 CHAR), 
	"LINE3" VARCHAR2(100 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKC90A760998518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_BANK_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_BANK_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_PERSON_NAME
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_PERSON_NAME" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"IS_DEFAULT" CHAR(1 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"FIRST_NAME" VARCHAR2(100 CHAR), 
	"KIM_NAME_TYPE" VARCHAR2(45 CHAR), 
	"LAST_NAME" VARCHAR2(100 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"MIDDLE_NAME" VARCHAR2(100 CHAR), 
	"SUFFIX" VARCHAR2(10 CHAR), 
	"TITLE" VARCHAR2(10 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FK45AEC02C98518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_INFORMATION
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_INFORMATION" 
   (	"TYPE" VARCHAR2(31 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACCESS_LEVEL" NUMBER(10,0), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"EFFECTIVE_DATE" TIMESTAMP (6), 
	"EXPIRATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"RESP_ENTITY" VARCHAR2(45 CHAR), 
	"SEVERITY" NUMBER(10,0), 
	"TEXT" VARCHAR2(4000 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	"TRN_ID_FK" NUMBER(19,0), 
	"FLAG_TYPE_ID_FK" NUMBER(19,0), 
	"NEXT_ID" NUMBER(19,0), 
	"PREV_ID" NUMBER(19,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKD2A2E003DBB2002A" FOREIGN KEY ("FLAG_TYPE_ID_FK")
	  REFERENCES "KSA"."KSSA_FLAG_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "FKD2A2E00316BC312E" FOREIGN KEY ("NEXT_ID")
	  REFERENCES "KSA"."KSSA_INFORMATION" ("ID") ENABLE, 
	 CONSTRAINT "FKD2A2E00395ACD1EE" FOREIGN KEY ("PREV_ID")
	  REFERENCES "KSA"."KSSA_INFORMATION" ("ID") ENABLE, 
	 CONSTRAINT "FKD2A2E00398518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE, 
	 CONSTRAINT "FKD2A2E003FE6E074B" FOREIGN KEY ("TRN_ID_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ACTIVITY" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ALTERED_ACNT_ID" VARCHAR2(255 CHAR), 
	"ALTERED_ENTITY_ID" VARCHAR2(45 CHAR), 
	"IP" VARCHAR2(32 CHAR), 
	"LOG_DETAIL" VARCHAR2(200 CHAR), 
	"MAC" VARCHAR2(12 CHAR), 
	"NEW_ATTRIBUTE" VARCHAR2(4000 CHAR), 
	"OLD_ATTRIBUTE" VARCHAR2(4000 CHAR), 
	"CREATION_DATE" TIMESTAMP (6), 
	"ACTIVITY_TYPE_ID_FK" NUMBER(19,0), 
	"CREATOR_ID" VARCHAR2(45), 
	"ALTERED_ENTITY" VARCHAR2(100), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ACNT
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ACNT" 
   (	"TYPE" VARCHAR2(31 CHAR) NOT NULL ENABLE, 
	"ID" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"CAN_AUTHENTICATE" CHAR(1 CHAR), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREDIT_LIMIT" NUMBER(19,2), 
	"ENTITY_ID" VARCHAR2(45 CHAR), 
	"IS_KIM_ACNT" CHAR(1 CHAR), 
	"LAST_KIM_UPDATE" TIMESTAMP (6), 
	"LATE1" NUMBER(19,2), 
	"LATE2" NUMBER(19,2), 
	"LATE3" NUMBER(19,2), 
	"DUE" NUMBER(19,2), 
	"LATE_LAST_UPDATE" TIMESTAMP (6), 
	"OUTSTANDING" NUMBER(19,2), 
	"LATE_PERIOD_ID_FK" NUMBER(19,0), 
	"ACNT_STATUS_TYPE_ID_FK" NUMBER(19,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKB8F79251AE7C54D4" FOREIGN KEY ("ACNT_STATUS_TYPE_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT_STATUS_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "FKB8F7925156D383B8" FOREIGN KEY ("LATE_PERIOD_ID_FK")
	  REFERENCES "KSA"."KSSA_LATE_PERIOD" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ACTIVITY_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ACTIVITY_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ALLOCATION" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AMNT" NUMBER(19,2), 
	"IS_LOCKED" CHAR(1 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	"TRN_ID_1_FK" NUMBER(19,0), 
	"TRN_ID_2_FK" NUMBER(19,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKC2912B0998518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE, 
	 CONSTRAINT "FKC2912B09ED7E538" FOREIGN KEY ("TRN_ID_2_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION" ("ID") ENABLE, 
	 CONSTRAINT "FKC2912B09ED770D9" FOREIGN KEY ("TRN_ID_1_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_GL_BREAKDOWN
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_GL_BREAKDOWN" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"GL_ACCOUNT" VARCHAR2(45 CHAR), 
	"BREAKDOWN" NUMBER(19,2), 
	"TRANSACTION_TYPE_ID_FK" VARCHAR2(20 CHAR), 
	"TRANSACTION_TYPE_SUB_CODE_FK" NUMBER(10,0), 
	"GL_TYPE_ID_FK" NUMBER(19,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKF48BE710AE27AC92" FOREIGN KEY ("TRANSACTION_TYPE_ID_FK", "TRANSACTION_TYPE_SUB_CODE_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION_TYPE" ("ID", "SUB_CODE") ENABLE, 
	 CONSTRAINT "FKF48BE710FA70171C" FOREIGN KEY ("GL_TYPE_ID_FK")
	  REFERENCES "KSA"."KSSA_GL_TYPE" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_TRANSACTION_TYPE_TAG
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_TRANSACTION_TYPE_TAG" 
   (	"TRANSACTION_TYPE_ID_FK" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_TYPE_SUB_CODE_FK" NUMBER(10,0) NOT NULL ENABLE, 
	"TAG_ID_FK" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "FKA1635C3F47AB5D71" FOREIGN KEY ("TAG_ID_FK")
	  REFERENCES "KSA"."KSSA_TAG" ("ID") ENABLE, 
	 CONSTRAINT "FKA1635C3FCE008744" FOREIGN KEY ("TRANSACTION_TYPE_ID_FK", "TRANSACTION_TYPE_SUB_CODE_FK")
	  REFERENCES "KSA"."KSSA_TRANSACTION_TYPE" ("ID", "SUB_CODE") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_SEQUENCE_TABLE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_SEQUENCE_TABLE" 
   (	"SEQ_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SEQ_VALUE" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("SEQ_NAME") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ACNT_PROTECTED_INFO
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ACNT_PROTECTED_INFO" 
   (	"ID" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"BANK_DETAILS" VARCHAR2(100 CHAR), 
	"TAX_REFERENCE" VARCHAR2(45 CHAR), 
	"BANK_TYPE_ID_FK" NUMBER(19,0), 
	"TAX_TYPE_ID_FK" NUMBER(19,0), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FKEF75726D2C28B62A" FOREIGN KEY ("BANK_TYPE_ID_FK")
	  REFERENCES "KSA"."KSSA_BANK_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "FKEF75726DACFC7690" FOREIGN KEY ("TAX_TYPE_ID_FK")
	  REFERENCES "KSA"."KSSA_TAX_TYPE" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_GL_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_GL_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_CURRENCY
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_CURRENCY" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	"ISO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID") ENABLE, 
	 UNIQUE ("ISO") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_TRANSACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_TRANSACTION_TYPE" 
   (	"TYPE" VARCHAR2(31 CHAR) NOT NULL ENABLE, 
	"ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"SUB_CODE" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DEF_TRN_TXT" VARCHAR2(100 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"END_DATE" TIMESTAMP (6), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"PRIORITY" NUMBER(10,0), 
	"AUTH_TXT" VARCHAR2(1000 CHAR), 
	"CLEAR_PERIOD" NUMBER(10,0), 
	"REFUND_RULE" VARCHAR2(2000 CHAR), 
	"DEF_ROLLUP_ID_FK" NUMBER(19,0), 
	 PRIMARY KEY ("ID", "SUB_CODE") ENABLE, 
	 CONSTRAINT "FK81104B8496077E1" FOREIGN KEY ("DEF_ROLLUP_ID_FK")
	  REFERENCES "KSA"."KSSA_ROLLUP" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ROLLUP
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ROLLUP" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_ELECTRONIC_CONTACT
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_ELECTRONIC_CONTACT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"IS_DEFAULT" CHAR(1 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"EMAIL_ADDRESS" VARCHAR2(255 CHAR), 
	"KIM_EMAIL_ADDRESS_TYPE" VARCHAR2(45 CHAR), 
	"KIM_PHONE_TYPE" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"PHONE_COUNTRY" VARCHAR2(5 CHAR), 
	"PHONE_EXTN" VARCHAR2(10 CHAR), 
	"PHONE_NUMBER" VARCHAR2(20 CHAR), 
	"ACNT_ID_FK" VARCHAR2(45 CHAR), 
	 PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "FK77758E6698518DD2" FOREIGN KEY ("ACNT_ID_FK")
	  REFERENCES "KSA"."KSSA_ACNT" ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_LATE_PERIOD
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_LATE_PERIOD" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	"DAYS_LATE1" NUMBER(10,0), 
	"DAYS_LATE2" NUMBER(10,0), 
	"DAYS_LATE3" NUMBER(10,0), 
	"IS_DEFAULT" CHAR(1 CHAR), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_FLAG_TYPE
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_FLAG_TYPE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(100 CHAR), 
	"ACCESS_LEVEL" NUMBER(10,0), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
--------------------------------------------------------
--  DDL for Table KSSA_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "KSA"."KSSA_DOCUMENT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DOCUMENT" VARCHAR2(255 CHAR), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATOR_ID" VARCHAR2(45 CHAR), 
	"EDIT_REASON" VARCHAR2(512 CHAR), 
	"EDITOR_ID" VARCHAR2(45 CHAR), 
	"LAST_UPDATE" TIMESTAMP (6), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;