//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 04:57:41 PM EST 
//


package com.sigmasys.kuali.ksa.model.export;

import java.math.BigDecimal;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for detailType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="detailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}universityFiscalAccountingPeriod"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}universityFiscalYear"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}createDate"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}chartOfAccountsCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}accountNumber"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}subAccountNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}objectCode"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}subObjectCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}balanceTypeCode"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}objectTypeCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}collectorDetailSequenceNumber"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}originationCode"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}documentTypeCode"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}documentNumber"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}amount"/>
 *         &lt;element ref="{http://www.kuali.org/kfs/gl/collector}detailText"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detailType", propOrder = {

})
public class DetailType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String universityFiscalAccountingPeriod;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String universityFiscalYear;

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createDate;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String chartOfAccountsCode;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String accountNumber;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subAccountNumber;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String objectCode;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subObjectCode;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String balanceTypeCode;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String objectTypeCode;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String collectorDetailSequenceNumber;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String originationCode;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String documentTypeCode;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String documentNumber;

    @XmlElement(required = true)
    protected BigDecimal amount;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String detailText;

    /**
     * Gets the value of the universityFiscalAccountingPeriod property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUniversityFiscalAccountingPeriod() {
        return universityFiscalAccountingPeriod;
    }

    /**
     * Sets the value of the universityFiscalAccountingPeriod property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUniversityFiscalAccountingPeriod(String value) {
        this.universityFiscalAccountingPeriod = value;
    }

    /**
     * Gets the value of the universityFiscalYear property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUniversityFiscalYear() {
        return universityFiscalYear;
    }

    /**
     * Sets the value of the universityFiscalYear property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUniversityFiscalYear(String value) {
        this.universityFiscalYear = value;
    }

    /**
     * Gets the value of the createDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the chartOfAccountsCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getChartOfAccountsCode() {
        return chartOfAccountsCode;
    }

    /**
     * Sets the value of the chartOfAccountsCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChartOfAccountsCode(String value) {
        this.chartOfAccountsCode = value;
    }

    /**
     * Gets the value of the accountNumber property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the subAccountNumber property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSubAccountNumber() {
        return subAccountNumber;
    }

    /**
     * Sets the value of the subAccountNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubAccountNumber(String value) {
        this.subAccountNumber = value;
    }

    /**
     * Gets the value of the objectCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getObjectCode() {
        return objectCode;
    }

    /**
     * Sets the value of the objectCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setObjectCode(String value) {
        this.objectCode = value;
    }

    /**
     * Gets the value of the subObjectCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSubObjectCode() {
        return subObjectCode;
    }

    /**
     * Sets the value of the subObjectCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubObjectCode(String value) {
        this.subObjectCode = value;
    }

    /**
     * Gets the value of the balanceTypeCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getBalanceTypeCode() {
        return balanceTypeCode;
    }

    /**
     * Sets the value of the balanceTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBalanceTypeCode(String value) {
        this.balanceTypeCode = value;
    }

    /**
     * Gets the value of the objectTypeCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getObjectTypeCode() {
        return objectTypeCode;
    }

    /**
     * Sets the value of the objectTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setObjectTypeCode(String value) {
        this.objectTypeCode = value;
    }

    /**
     * Gets the value of the collectorDetailSequenceNumber property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCollectorDetailSequenceNumber() {
        return collectorDetailSequenceNumber;
    }

    /**
     * Sets the value of the collectorDetailSequenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCollectorDetailSequenceNumber(String value) {
        this.collectorDetailSequenceNumber = value;
    }

    /**
     * Gets the value of the originationCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOriginationCode() {
        return originationCode;
    }

    /**
     * Sets the value of the originationCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOriginationCode(String value) {
        this.originationCode = value;
    }

    /**
     * Gets the value of the documentTypeCode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDocumentTypeCode() {
        return documentTypeCode;
    }

    /**
     * Sets the value of the documentTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentTypeCode(String value) {
        this.documentTypeCode = value;
    }

    /**
     * Gets the value of the documentNumber property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the detailText property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDetailText() {
        return detailText;
    }

    /**
     * Sets the value of the detailText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDetailText(String value) {
        this.detailText = value;
    }

}
