//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.17 at 02:47:07 PM EDT 
//

package com.sigmasys.kuali.ksa.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="period-length" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="period-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "periodLengthAndPeriodBalance"
})
@XmlRootElement(name = "aged-balance")
public class AgedBalance {

    @XmlElements({
            @XmlElement(name = "period-length", required = true, type = Integer.class),
            @XmlElement(name = "period-balance", required = true, type = BigDecimal.class)
    })
    protected List<Comparable> periodLengthAndPeriodBalance;

    /**
     * Gets the value of the periodLengthAndPeriodBalance property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodLengthAndPeriodBalance property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodLengthAndPeriodBalance().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * {@link BigDecimal }
     */
    public List<Comparable> getPeriodLengthAndPeriodBalance() {
        if (periodLengthAndPeriodBalance == null) {
            periodLengthAndPeriodBalance = new ArrayList<Comparable>();
        }
        return this.periodLengthAndPeriodBalance;
    }

}
