//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 09:08:39 PM GMT-05:00 
//


package com.sigmasys.kuali.ksa.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reporting-period">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="start-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="end-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="general-ledger-report-entry">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="general-ledger-account" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="general-ledger-operation">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="credit"/>
 *                         &lt;enumeration value="debit"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="system" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="transaction-identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;element name="transaction-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="transmission-identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="transmission-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="transmission-time" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="batch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="transmission-result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="transmission-period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "reportingPeriod",
        "generalLedgerReportEntry"
})
@XmlRootElement(name = "general-ledger-report")
public class GeneralLedgerReport {

    @XmlElement(name = "reporting-period", required = true)
    protected ReportingPeriod reportingPeriod;
    @XmlElement(name = "general-ledger-report-entry", required = true)
    protected GeneralLedgerReport.GeneralLedgerReportEntry generalLedgerReportEntry;

    /**
     * Gets the value of the reportingPeriod property.
     *
     * @return possible object is
     *         {@link ReportingPeriod }
     */
    public ReportingPeriod getReportingPeriod() {
        return reportingPeriod;
    }

    /**
     * Sets the value of the reportingPeriod property.
     *
     * @param value allowed object is
     *              {@link ReportingPeriod }
     */
    public void setReportingPeriod(ReportingPeriod value) {
        this.reportingPeriod = value;
    }

    /**
     * Gets the value of the generalLedgerReportEntry property.
     *
     * @return possible object is
     *         {@link GeneralLedgerReport.GeneralLedgerReportEntry }
     */
    public GeneralLedgerReport.GeneralLedgerReportEntry getGeneralLedgerReportEntry() {
        return generalLedgerReportEntry;
    }

    /**
     * Sets the value of the generalLedgerReportEntry property.
     *
     * @param value allowed object is
     *              {@link GeneralLedgerReport.GeneralLedgerReportEntry }
     */
    public void setGeneralLedgerReportEntry(GeneralLedgerReport.GeneralLedgerReportEntry value) {
        this.generalLedgerReportEntry = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="general-ledger-account" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="general-ledger-operation">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="credit"/>
     *               &lt;enumeration value="debit"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="system" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="transaction-identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;element name="transaction-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="transmission-identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="transmission-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="transmission-time" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="batch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="transmission-result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="transmission-period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "generalLedgerAccount",
            "date",
            "generalLedgerOperation",
            "amount",
            "system",
            "transactionIdentifier",
            "transactionStatus",
            "transmissionIdentifier",
            "transmissionDate",
            "transmissionTime",
            "batch",
            "transmissionResult",
            "transmissionPeriod"
    })
    public static class GeneralLedgerReportEntry {

        @XmlElement(name = "general-ledger-account", required = true)
        protected String generalLedgerAccount;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "general-ledger-operation", required = true)
        protected String generalLedgerOperation;
        @XmlElement(required = true)
        protected BigDecimal amount;
        @XmlElement(required = true)
        protected String system;
        @XmlElement(name = "transaction-identifier", required = true)
        protected List<String> transactionIdentifier;
        @XmlElement(name = "transaction-status", required = true)
        protected String transactionStatus;
        @XmlElement(name = "transmission-identifier")
        protected String transmissionIdentifier;
        @XmlElement(name = "transmission-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar transmissionDate;
        @XmlElement(name = "transmission-time")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar transmissionTime;
        protected String batch;
        @XmlElement(name = "transmission-result")
        protected String transmissionResult;
        @XmlElement(name = "transmission-period")
        protected String transmissionPeriod;

        /**
         * Gets the value of the generalLedgerAccount property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getGeneralLedgerAccount() {
            return generalLedgerAccount;
        }

        /**
         * Sets the value of the generalLedgerAccount property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setGeneralLedgerAccount(String value) {
            this.generalLedgerAccount = value;
        }

        /**
         * Gets the value of the date property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the generalLedgerOperation property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getGeneralLedgerOperation() {
            return generalLedgerOperation;
        }

        /**
         * Sets the value of the generalLedgerOperation property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setGeneralLedgerOperation(String value) {
            this.generalLedgerOperation = value;
        }

        /**
         * Gets the value of the amount property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the system property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSystem(String value) {
            this.system = value;
        }

        /**
         * Gets the value of the transactionIdentifier property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transactionIdentifier property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransactionIdentifier().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getTransactionIdentifier() {
            if (transactionIdentifier == null) {
                transactionIdentifier = new ArrayList<String>();
            }
            return this.transactionIdentifier;
        }

        /**
         * Gets the value of the transactionStatus property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransactionStatus() {
            return transactionStatus;
        }

        /**
         * Sets the value of the transactionStatus property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransactionStatus(String value) {
            this.transactionStatus = value;
        }

        /**
         * Gets the value of the transmissionIdentifier property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransmissionIdentifier() {
            return transmissionIdentifier;
        }

        /**
         * Sets the value of the transmissionIdentifier property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransmissionIdentifier(String value) {
            this.transmissionIdentifier = value;
        }

        /**
         * Gets the value of the transmissionDate property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getTransmissionDate() {
            return transmissionDate;
        }

        /**
         * Sets the value of the transmissionDate property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setTransmissionDate(XMLGregorianCalendar value) {
            this.transmissionDate = value;
        }

        /**
         * Gets the value of the transmissionTime property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getTransmissionTime() {
            return transmissionTime;
        }

        /**
         * Sets the value of the transmissionTime property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setTransmissionTime(XMLGregorianCalendar value) {
            this.transmissionTime = value;
        }

        /**
         * Gets the value of the batch property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getBatch() {
            return batch;
        }

        /**
         * Sets the value of the batch property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setBatch(String value) {
            this.batch = value;
        }

        /**
         * Gets the value of the transmissionResult property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransmissionResult() {
            return transmissionResult;
        }

        /**
         * Sets the value of the transmissionResult property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransmissionResult(String value) {
            this.transmissionResult = value;
        }

        /**
         * Gets the value of the transmissionPeriod property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransmissionPeriod() {
            return transmissionPeriod;
        }

        /**
         * Sets the value of the transmissionPeriod property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransmissionPeriod(String value) {
            this.transmissionPeriod = value;
        }

    }

}
