//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 09:08:39 PM GMT-05:00 
//


package com.sigmasys.kuali.ksa.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="form-year" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="form-checkboxes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="void" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="corrected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="reporting-method-changed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="filer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{}postal-address"/>
 *                   &lt;element name="telephone-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fein" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="student">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{}postal-address"/>
 *                   &lt;element name="social-security-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="account-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="half-time" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="graduate-student" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="financial">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="payments-received" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                     &lt;element name="amount-billed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;/choice>
 *                   &lt;element name="includes-next-quarter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="prior-year-adjustment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="scholarships-or-grants" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="prior-year-scholarship-adjustment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="insurance-contract" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "formYear",
        "formCheckboxes",
        "filer",
        "student",
        "financial"
})
@XmlRootElement(name = "irs-1098-t")
public class Irs1098T {

    @XmlElement(name = "form-year", required = true)
    protected String formYear;
    @XmlElement(name = "form-checkboxes", required = true)
    protected Irs1098T.FormCheckboxes formCheckboxes;
    @XmlElement(required = true)
    protected Irs1098T.Filer filer;
    @XmlElement(required = true)
    protected Irs1098T.Student student;
    @XmlElement(required = true)
    protected Irs1098T.Financial financial;

    /**
     * Gets the value of the formYear property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFormYear() {
        return formYear;
    }

    /**
     * Sets the value of the formYear property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormYear(String value) {
        this.formYear = value;
    }

    /**
     * Gets the value of the formCheckboxes property.
     *
     * @return possible object is
     *         {@link Irs1098T.FormCheckboxes }
     */
    public Irs1098T.FormCheckboxes getFormCheckboxes() {
        return formCheckboxes;
    }

    /**
     * Sets the value of the formCheckboxes property.
     *
     * @param value allowed object is
     *              {@link Irs1098T.FormCheckboxes }
     */
    public void setFormCheckboxes(Irs1098T.FormCheckboxes value) {
        this.formCheckboxes = value;
    }

    /**
     * Gets the value of the filer property.
     *
     * @return possible object is
     *         {@link Irs1098T.Filer }
     */
    public Irs1098T.Filer getFiler() {
        return filer;
    }

    /**
     * Sets the value of the filer property.
     *
     * @param value allowed object is
     *              {@link Irs1098T.Filer }
     */
    public void setFiler(Irs1098T.Filer value) {
        this.filer = value;
    }

    /**
     * Gets the value of the student property.
     *
     * @return possible object is
     *         {@link Irs1098T.Student }
     */
    public Irs1098T.Student getStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     *
     * @param value allowed object is
     *              {@link Irs1098T.Student }
     */
    public void setStudent(Irs1098T.Student value) {
        this.student = value;
    }

    /**
     * Gets the value of the financial property.
     *
     * @return possible object is
     *         {@link Irs1098T.Financial }
     */
    public Irs1098T.Financial getFinancial() {
        return financial;
    }

    /**
     * Sets the value of the financial property.
     *
     * @param value allowed object is
     *              {@link Irs1098T.Financial }
     */
    public void setFinancial(Irs1098T.Financial value) {
        this.financial = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{}postal-address"/>
     *         &lt;element name="telephone-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fein" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "name",
            "postalAddress",
            "telephoneNumber",
            "fein"
    })
    public static class Filer {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "postal-address", required = true)
        protected PostalAddress postalAddress;
        @XmlElement(name = "telephone-number", required = true)
        protected String telephoneNumber;
        @XmlElement(name = "fein", required = true)
        protected String fein;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the telephoneNumber property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTelephoneNumber() {
            return telephoneNumber;
        }

        /**
         * Sets the value of the telephoneNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTelephoneNumber(String value) {
            this.telephoneNumber = value;
        }

        /**
         * Gets the value of the fein property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getFein() {
            return fein;
        }

        /**
         * Sets the value of the fein property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFein(String value) {
            this.fein = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="payments-received" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *           &lt;element name="amount-billed" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;/choice>
     *         &lt;element name="includes-next-quarter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="prior-year-adjustment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="scholarships-or-grants" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="prior-year-scholarship-adjustment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="insurance-contract" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "paymentsReceived",
            "amountBilled",
            "includesNextQuarter",
            "priorYearAdjustment",
            "scholarshipsOrGrants",
            "priorYearScholarshipAdjustment",
            "insuranceContract"
    })
    public static class Financial {

        @XmlElement(name = "payments-received")
        protected BigDecimal paymentsReceived;
        @XmlElement(name = "amount-billed")
        protected BigDecimal amountBilled;
        @XmlElement(name = "includes-next-quarter")
        protected boolean includesNextQuarter;
        @XmlElement(name = "prior-year-adjustment", required = true)
        protected BigDecimal priorYearAdjustment;
        @XmlElement(name = "scholarships-or-grants", required = true)
        protected BigDecimal scholarshipsOrGrants;
        @XmlElement(name = "prior-year-scholarship-adjustment", required = true)
        protected BigDecimal priorYearScholarshipAdjustment;
        @XmlElement(name = "insurance-contract", required = true)
        protected BigDecimal insuranceContract;

        /**
         * Gets the value of the paymentsReceived property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getPaymentsReceived() {
            return paymentsReceived;
        }

        /**
         * Sets the value of the paymentsReceived property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setPaymentsReceived(BigDecimal value) {
            this.paymentsReceived = value;
        }

        /**
         * Gets the value of the amountBilled property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getAmountBilled() {
            return amountBilled;
        }

        /**
         * Sets the value of the amountBilled property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setAmountBilled(BigDecimal value) {
            this.amountBilled = value;
        }

        /**
         * Gets the value of the includesNextQuarter property.
         */
        public boolean isIncludesNextQuarter() {
            return includesNextQuarter;
        }

        /**
         * Sets the value of the includesNextQuarter property.
         */
        public void setIncludesNextQuarter(boolean value) {
            this.includesNextQuarter = value;
        }

        /**
         * Gets the value of the priorYearAdjustment property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getPriorYearAdjustment() {
            return priorYearAdjustment;
        }

        /**
         * Sets the value of the priorYearAdjustment property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setPriorYearAdjustment(BigDecimal value) {
            this.priorYearAdjustment = value;
        }

        /**
         * Gets the value of the scholarshipsOrGrants property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getScholarshipsOrGrants() {
            return scholarshipsOrGrants;
        }

        /**
         * Sets the value of the scholarshipsOrGrants property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setScholarshipsOrGrants(BigDecimal value) {
            this.scholarshipsOrGrants = value;
        }

        /**
         * Gets the value of the priorYearScholarshipAdjustment property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getPriorYearScholarshipAdjustment() {
            return priorYearScholarshipAdjustment;
        }

        /**
         * Sets the value of the priorYearScholarshipAdjustment property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setPriorYearScholarshipAdjustment(BigDecimal value) {
            this.priorYearScholarshipAdjustment = value;
        }

        /**
         * Gets the value of the insuranceContract property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getInsuranceContract() {
            return insuranceContract;
        }

        /**
         * Sets the value of the insuranceContract property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setInsuranceContract(BigDecimal value) {
            this.insuranceContract = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="void" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="corrected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="reporting-method-changed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "_void",
            "corrected",
            "reportingMethodChanged"
    })
    public static class FormCheckboxes {

        @XmlElement(name = "void")
        protected boolean _void;
        protected boolean corrected;
        @XmlElement(name = "reporting-method-changed")
        protected boolean reportingMethodChanged;

        /**
         * Gets the value of the void property.
         */
        public boolean isVoid() {
            return _void;
        }

        /**
         * Sets the value of the void property.
         */
        public void setVoid(boolean value) {
            this._void = value;
        }

        /**
         * Gets the value of the corrected property.
         */
        public boolean isCorrected() {
            return corrected;
        }

        /**
         * Sets the value of the corrected property.
         */
        public void setCorrected(boolean value) {
            this.corrected = value;
        }

        /**
         * Gets the value of the reportingMethodChanged property.
         */
        public boolean isReportingMethodChanged() {
            return reportingMethodChanged;
        }

        /**
         * Sets the value of the reportingMethodChanged property.
         */
        public void setReportingMethodChanged(boolean value) {
            this.reportingMethodChanged = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{}postal-address"/>
     *         &lt;element name="social-security-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="account-number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="half-time" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="graduate-student" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "name",
            "postalAddress",
            "socialSecurityNumber",
            "accountNumber",
            "halfTime",
            "graduateStudent"
    })
    public static class Student {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "postal-address", required = true)
        protected PostalAddress postalAddress;
        @XmlElement(name = "social-security-number", required = true)
        protected String socialSecurityNumber;
        @XmlElement(name = "account-number", required = true)
        protected String accountNumber;
        @XmlElement(name = "half-time")
        protected boolean halfTime;
        @XmlElement(name = "graduate-student")
        protected boolean graduateStudent;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the socialSecurityNumber property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getSocialSecurityNumber() {
            return socialSecurityNumber;
        }

        /**
         * Sets the value of the socialSecurityNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSocialSecurityNumber(String value) {
            this.socialSecurityNumber = value;
        }

        /**
         * Gets the value of the accountNumber property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAccountNumber(String value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the halfTime property.
         */
        public boolean isHalfTime() {
            return halfTime;
        }

        /**
         * Sets the value of the halfTime property.
         */
        public void setHalfTime(boolean value) {
            this.halfTime = value;
        }

        /**
         * Gets the value of the graduateStudent property.
         */
        public boolean isGraduateStudent() {
            return graduateStudent;
        }

        /**
         * Sets the value of the graduateStudent property.
         */
        public void setGraduateStudent(boolean value) {
            this.graduateStudent = value;
        }

    }

}
