//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 06:19:05 PM EDT 
//


package com.sigmasys.kuali.ksa.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="amends"/>
 *               &lt;enumeration value="suspicious"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="payer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}person-name"/>
 *                   &lt;element ref="{}postal-address"/>
 *                   &lt;element name="identity" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tax-identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="date-of-birth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="identity-document" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="id-issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="id-serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transaction-description">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="total-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="multiple-payments" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="total-price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="detail">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="financial-breakdown">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence maxOccurs="unbounded">
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="serials" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;choice>
 *                               &lt;element name="type">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="personalproperty"/>
 *                                     &lt;enumeration value="realproperty"/>
 *                                     &lt;enumeration value="personalservice"/>
 *                                     &lt;enumeration value="businessservice"/>
 *                                     &lt;enumeration value="intangibleproperty"/>
 *                                     &lt;enumeration value="debtobligation"/>
 *                                     &lt;enumeration value="exchangeofcash"/>
 *                                     &lt;enumeration value="escrow"/>
 *                                     &lt;enumeration value="bail"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="other-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="filer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="business-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="fein" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element ref="{}postal-address"/>
 *                   &lt;element name="nature-of-business" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "type",
        "payer",
        "transactionDescription",
        "filer"
})
@XmlRootElement(name = "irs-8300")
public class Irs8300 {

    @XmlElement(required = false)
    protected String type;
    @XmlElement(required = true)
    protected Payer payer;
    @XmlElement(name = "transaction-description", required = true)
    protected TransactionDescription transactionDescription;
    @XmlElement(required = true)
    protected Filer filer;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the payer property.
     *
     * @return possible object is
     *         {@link Irs8300 .Payer }
     */
    public Irs8300.Payer getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     *
     * @param value allowed object is
     *              {@link Irs8300 .Payer }
     */
    public void setPayer(Irs8300.Payer value) {
        this.payer = value;
    }

    /**
     * Gets the value of the transactionDescription property.
     *
     * @return possible object is
     *         {@link Irs8300.TransactionDescription }
     */
    public Irs8300.TransactionDescription getTransactionDescription() {
        return transactionDescription;
    }

    /**
     * Sets the value of the transactionDescription property.
     *
     * @param value allowed object is
     *              {@link Irs8300.TransactionDescription }
     */
    public void setTransactionDescription(Irs8300.TransactionDescription value) {
        this.transactionDescription = value;
    }

    /**
     * Gets the value of the filer property.
     *
     * @return possible object is
     *         {@link com.sigmasys.kuali.ksa.jaxb.Irs8300.Filer }
     */
    public Filer getFiler() {
        return filer;
    }

    /**
     * Sets the value of the filer property.
     *
     * @param value allowed object is
     *              {@link com.sigmasys.kuali.ksa.jaxb.Irs8300.Filer }
     */
    public void setFiler(Filer value) {
        this.filer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}person-name"/>
     *         &lt;element ref="{}postal-address"/>
     *         &lt;element name="identity" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tax-identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="date-of-birth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="identity-document" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="id-issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="id-serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "personName",
            "postalAddress",
            "identity"
    })
    public static class Payer {

        @XmlElement(name = "person-name", required = true)
        protected PersonName personName;
        @XmlElement(name = "postal-address", required = true)
        protected PostalAddress postalAddress;
        protected Irs8300.Payer.Identity identity;

        /**
         * Gets the value of the personName property.
         *
         * @return possible object is
         *         {@link PersonName }
         */
        public PersonName getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         *
         * @param value allowed object is
         *              {@link PersonName }
         */
        public void setPersonName(PersonName value) {
            this.personName = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the identity property.
         *
         * @return possible object is
         *         {@link Irs8300.Payer.Identity }
         */
        public Irs8300.Payer.Identity getIdentity() {
            return identity;
        }

        /**
         * Sets the value of the identity property.
         *
         * @param value allowed object is
         *              {@link Irs8300.Payer.Identity }
         */
        public void setIdentity(Irs8300.Payer.Identity value) {
            this.identity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tax-identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="date-of-birth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="identity-document" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="id-issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="id-serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "taxIdentifier",
                "dateOfBirth",
                "occupation",
                "identityDocument"
        })
        public static class Identity {

            @XmlElement(name = "tax-identifier")
            protected String taxIdentifier;
            @XmlElement(name = "date-of-birth")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateOfBirth;
            protected String occupation;
            @XmlElement(name = "identity-document")
            protected Irs8300.Payer.Identity.IdentityDocument identityDocument;

            /**
             * Gets the value of the taxIdentifier property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getTaxIdentifier() {
                return taxIdentifier;
            }

            /**
             * Sets the value of the taxIdentifier property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setTaxIdentifier(String value) {
                this.taxIdentifier = value;
            }

            /**
             * Gets the value of the dateOfBirth property.
             *
             * @return possible object is
             *         {@link javax.xml.datatype.XMLGregorianCalendar }
             */
            public XMLGregorianCalendar getDateOfBirth() {
                return dateOfBirth;
            }

            /**
             * Sets the value of the dateOfBirth property.
             *
             * @param value allowed object is
             *              {@link javax.xml.datatype.XMLGregorianCalendar }
             */
            public void setDateOfBirth(XMLGregorianCalendar value) {
                this.dateOfBirth = value;
            }

            /**
             * Gets the value of the occupation property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getOccupation() {
                return occupation;
            }

            /**
             * Sets the value of the occupation property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setOccupation(String value) {
                this.occupation = value;
            }

            /**
             * Gets the value of the identityDocument property.
             *
             * @return possible object is
             *         {@link Irs8300.Payer.Identity.IdentityDocument }
             */
            public Irs8300.Payer.Identity.IdentityDocument getIdentityDocument() {
                return identityDocument;
            }

            /**
             * Sets the value of the identityDocument property.
             *
             * @param value allowed object is
             *              {@link Irs8300 .Payer.Identity.IdentityDocument }
             */
            public void setIdentityDocument(Irs8300.Payer.Identity.IdentityDocument value) {
                this.identityDocument = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * <p/>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p/>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="id-issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="id-serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "idType",
                    "idIssuer",
                    "idSerial"
            })
            public static class IdentityDocument {

                @XmlElement(name = "id-type", required = true)
                protected String idType;
                @XmlElement(name = "id-issuer", required = true)
                protected String idIssuer;
                @XmlElement(name = "id-serial", required = true)
                protected String idSerial;

                /**
                 * Gets the value of the idType property.
                 *
                 * @return possible object is
                 *         {@link String }
                 */
                public String getIdType() {
                    return idType;
                }

                /**
                 * Sets the value of the idType property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setIdType(String value) {
                    this.idType = value;
                }

                /**
                 * Gets the value of the idIssuer property.
                 *
                 * @return possible object is
                 *         {@link String }
                 */
                public String getIdIssuer() {
                    return idIssuer;
                }

                /**
                 * Sets the value of the idIssuer property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setIdIssuer(String value) {
                    this.idIssuer = value;
                }

                /**
                 * Gets the value of the idSerial property.
                 *
                 * @return possible object is
                 *         {@link String }
                 */
                public String getIdSerial() {
                    return idSerial;
                }

                /**
                 * Sets the value of the idSerial property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setIdSerial(String value) {
                    this.idSerial = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="business-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="fein" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element ref="{}postal-address"/>
     *         &lt;element name="nature-of-business" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "businessName",
            "fein",
            "ssn",
            "postalAddress",
            "natureOfBusiness"
    })
    public static class Filer {

        @XmlElement(name = "business-name", required = true)
        protected String businessName;
        protected String fein;
        protected String ssn;
        @XmlElement(name = "postal-address", required = true)
        protected PostalAddress postalAddress;
        @XmlElement(name = "nature-of-business", required = true)
        protected String natureOfBusiness;

        /**
         * Gets the value of the businessName property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getBusinessName() {
            return businessName;
        }

        /**
         * Sets the value of the businessName property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setBusinessName(String value) {
            this.businessName = value;
        }

        /**
         * Gets the value of the fein property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getFein() {
            return fein;
        }

        /**
         * Sets the value of the fein property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFein(String value) {
            this.fein = value;
        }

        /**
         * Gets the value of the ssn property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getSsn() {
            return ssn;
        }

        /**
         * Sets the value of the ssn property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSsn(String value) {
            this.ssn = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the natureOfBusiness property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getNatureOfBusiness() {
            return natureOfBusiness;
        }

        /**
         * Sets the value of the natureOfBusiness property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setNatureOfBusiness(String value) {
            this.natureOfBusiness = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="total-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="multiple-payments" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="total-price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="detail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="financial-breakdown">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence maxOccurs="unbounded">
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="serials" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;choice>
     *                     &lt;element name="type">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;enumeration value="personalproperty"/>
     *                           &lt;enumeration value="realproperty"/>
     *                           &lt;enumeration value="personalservice"/>
     *                           &lt;enumeration value="businessservice"/>
     *                           &lt;enumeration value="intangibleproperty"/>
     *                           &lt;enumeration value="debtobligation"/>
     *                           &lt;enumeration value="exchangeofcash"/>
     *                           &lt;enumeration value="escrow"/>
     *                           &lt;enumeration value="bail"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                     &lt;element name="other-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "date",
            "totalAmount",
            "multiplePayments",
            "totalPrice",
            "detail"
    })
    public static class TransactionDescription {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "total-amount", required = true)
        protected BigDecimal totalAmount;
        @XmlElement(name = "multiple-payments")
        protected boolean multiplePayments;
        @XmlElement(name = "total-price", required = true)
        protected BigDecimal totalPrice;
        @XmlElement(required = true)
        protected Detail detail;

        /**
         * Gets the value of the date property.
         *
         * @return possible object is
         *         {@link javax.xml.datatype.XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value allowed object is
         *              {@link javax.xml.datatype.XMLGregorianCalendar }
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the totalAmount property.
         *
         * @return possible object is
         *         {@link java.math.BigDecimal }
         */
        public BigDecimal getTotalAmount() {
            return totalAmount;
        }

        /**
         * Sets the value of the totalAmount property.
         *
         * @param value allowed object is
         *              {@link java.math.BigDecimal }
         */
        public void setTotalAmount(BigDecimal value) {
            this.totalAmount = value;
        }

        /**
         * Gets the value of the multiplePayments property.
         */
        public boolean isMultiplePayments() {
            return multiplePayments;
        }

        /**
         * Sets the value of the multiplePayments property.
         */
        public void setMultiplePayments(boolean value) {
            this.multiplePayments = value;
        }

        /**
         * Gets the value of the totalPrice property.
         *
         * @return possible object is
         *         {@link java.math.BigDecimal }
         */
        public BigDecimal getTotalPrice() {
            return totalPrice;
        }

        /**
         * Sets the value of the totalPrice property.
         *
         * @param value allowed object is
         *              {@link java.math.BigDecimal }
         */
        public void setTotalPrice(BigDecimal value) {
            this.totalPrice = value;
        }

        /**
         * Gets the value of the detail property.
         *
         * @return possible object is
         *         {@link Irs8300.TransactionDescription.Detail }
         */
        public Irs8300.TransactionDescription.Detail getDetail() {
            return detail;
        }

        /**
         * Sets the value of the detail property.
         *
         * @param value allowed object is
         *              {@link Irs8300.TransactionDescription.Detail }
         */
        public void setDetail(Irs8300.TransactionDescription.Detail value) {
            this.detail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="financial-breakdown">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence maxOccurs="unbounded">
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="serials" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;choice>
         *           &lt;element name="type">
         *             &lt;simpleType>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                 &lt;enumeration value="personalproperty"/>
         *                 &lt;enumeration value="realproperty"/>
         *                 &lt;enumeration value="personalservice"/>
         *                 &lt;enumeration value="businessservice"/>
         *                 &lt;enumeration value="intangibleproperty"/>
         *                 &lt;enumeration value="debtobligation"/>
         *                 &lt;enumeration value="exchangeofcash"/>
         *                 &lt;enumeration value="escrow"/>
         *                 &lt;enumeration value="bail"/>
         *               &lt;/restriction>
         *             &lt;/simpleType>
         *           &lt;/element>
         *           &lt;element name="other-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "financialBreakdown",
                "serials",
                "type",
                "otherType"
        })
        public static class Detail {

            @XmlElement(name = "financial-breakdown", required = true)
            protected FinancialBreakdown financialBreakdown;
            @XmlElement(required = true)
            protected String serials;
            protected String type;
            @XmlElement(name = "other-type", required = false)
            protected String otherType;

            /**
             * Gets the value of the financialBreakdown property.
             *
             * @return possible object is
             *         {@link Irs8300 .TransactionDescription.Detail.FinancialBreakdown }
             */
            public Irs8300.TransactionDescription.Detail.FinancialBreakdown getFinancialBreakdown() {
                return financialBreakdown;
            }

            /**
             * Sets the value of the financialBreakdown property.
             *
             * @param value allowed object is
             *              {@link Irs8300 .TransactionDescription.Detail.FinancialBreakdown }
             */
            public void setFinancialBreakdown(Irs8300.TransactionDescription.Detail.FinancialBreakdown value) {
                this.financialBreakdown = value;
            }

            /**
             * Gets the value of the serials property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getSerials() {
                return serials;
            }

            /**
             * Sets the value of the serials property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setSerials(String value) {
                this.serials = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the otherType property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getOtherType() {
                return otherType;
            }

            /**
             * Sets the value of the otherType property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setOtherType(String value) {
                this.otherType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * <p/>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p/>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence maxOccurs="unbounded">
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "typeAndAmountAndNativeAmount"
            })
            public static class FinancialBreakdown {

                @XmlElementRefs({
                        @XmlElementRef(name = "amount", type = JAXBElement.class),
                        @XmlElementRef(name = "type", type = JAXBElement.class),
                        @XmlElementRef(name = "native-amount", type = JAXBElement.class)
                })
                protected List<JAXBElement<? extends Serializable>> typeAndAmountAndNativeAmount;

                /**
                 * Gets the value of the typeAndAmountAndNativeAmount property.
                 * <p/>
                 * <p/>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the typeAndAmountAndNativeAmount property.
                 * <p/>
                 * <p/>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTypeAndAmountAndNativeAmount().add(newItem);
                 * </pre>
                 * <p/>
                 * <p/>
                 * <p/>
                 * Objects of the following type(s) are allowed in the list
                 * {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
                 * {@link javax.xml.bind.JAXBElement }{@code <}{@link java.math.BigDecimal }{@code >}
                 * {@link javax.xml.bind.JAXBElement }{@code <}{@link java.math.BigDecimal }{@code >}
                 */
                public List<JAXBElement<? extends Serializable>> getTypeAndAmountAndNativeAmount() {
                    if (typeAndAmountAndNativeAmount == null) {
                        typeAndAmountAndNativeAmount = new ArrayList<JAXBElement<? extends Serializable>>();
                    }
                    return this.typeAndAmountAndNativeAmount;
                }

            }

        }

    }

}
