//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 04:56:14 PM EDT 
//


package com.sigmasys.kuali.ksa.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preferred-delivery-mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bill-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cycle">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="bill-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="bill-generated" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="bill-start" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="bill-end" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="balances">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="with-deferments">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}aged-balance"/>
 *                             &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="total-deferred" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="has-expired-deferment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="without-deferments">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}aged-balance"/>
 *                             &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="account-owner">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account-identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{}person-name"/>
 *                   &lt;element ref="{}postal-address"/>
 *                   &lt;element ref="{}electronic-contact"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bill-recipient" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}person-name"/>
 *                   &lt;element ref="{}postal-address" minOccurs="0"/>
 *                   &lt;element ref="{}electronic-contact" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}transaction-list"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "preferredDeliveryMode",
        "billId",
        "cycle",
        "balances",
        "accountOwner",
        "billRecipient",
        "transactionList",
        "message"
})
@XmlRootElement(name = "ksa-bill")
public class KsaBill {

    @XmlElement(name = "preferred-delivery-mode", required = true)
    protected String preferredDeliveryMode;
    @XmlElement(name = "bill-id", required = true)
    protected String billId;
    @XmlElement(required = true)
    protected KsaBill.Cycle cycle;
    @XmlElement(required = true)
    protected KsaBill.Balances balances;
    @XmlElement(name = "account-owner", required = true)
    protected KsaBill.AccountOwner accountOwner;
    @XmlElement(name = "bill-recipient")
    protected KsaBill.BillRecipient billRecipient;
    @XmlElement(name = "transaction-list", required = true)
    protected TransactionList transactionList;
    protected String message;

    /**
     * Gets the value of the preferredDeliveryMode property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPreferredDeliveryMode() {
        return preferredDeliveryMode;
    }

    /**
     * Sets the value of the preferredDeliveryMode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPreferredDeliveryMode(String value) {
        this.preferredDeliveryMode = value;
    }

    /**
     * Gets the value of the billId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getBillId() {
        return billId;
    }

    /**
     * Sets the value of the billId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBillId(String value) {
        this.billId = value;
    }

    /**
     * Gets the value of the cycle property.
     *
     * @return possible object is
     *         {@link KsaBill.Cycle }
     */
    public KsaBill.Cycle getCycle() {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     *
     * @param value allowed object is
     *              {@link KsaBill.Cycle }
     */
    public void setCycle(KsaBill.Cycle value) {
        this.cycle = value;
    }

    /**
     * Gets the value of the balances property.
     *
     * @return possible object is
     *         {@link KsaBill.Balances }
     */
    public KsaBill.Balances getBalances() {
        return balances;
    }

    /**
     * Sets the value of the balances property.
     *
     * @param value allowed object is
     *              {@link KsaBill.Balances }
     */
    public void setBalances(KsaBill.Balances value) {
        this.balances = value;
    }

    /**
     * Gets the value of the accountOwner property.
     *
     * @return possible object is
     *         {@link KsaBill.AccountOwner }
     */
    public KsaBill.AccountOwner getAccountOwner() {
        return accountOwner;
    }

    /**
     * Sets the value of the accountOwner property.
     *
     * @param value allowed object is
     *              {@link KsaBill.AccountOwner }
     */
    public void setAccountOwner(KsaBill.AccountOwner value) {
        this.accountOwner = value;
    }

    /**
     * Gets the value of the billRecipient property.
     *
     * @return possible object is
     *         {@link KsaBill.BillRecipient }
     */
    public KsaBill.BillRecipient getBillRecipient() {
        return billRecipient;
    }

    /**
     * Sets the value of the billRecipient property.
     *
     * @param value allowed object is
     *              {@link KsaBill.BillRecipient }
     */
    public void setBillRecipient(KsaBill.BillRecipient value) {
        this.billRecipient = value;
    }

    /**
     * Gets the value of the transactionList property.
     *
     * @return possible object is
     *         {@link TransactionList }
     */
    public TransactionList getTransactionList() {
        return transactionList;
    }

    /**
     * Sets the value of the transactionList property.
     *
     * @param value allowed object is
     *              {@link TransactionList }
     */
    public void setTransactionList(TransactionList value) {
        this.transactionList = value;
    }

    /**
     * Gets the value of the message property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessage(String value) {
        this.message = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="account-identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{}person-name"/>
     *         &lt;element ref="{}postal-address"/>
     *         &lt;element ref="{}electronic-contact"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "accountIdentifier",
            "personName",
            "postalAddress",
            "electronicContact"
    })
    public static class AccountOwner {

        @XmlElement(name = "account-identifier", required = true)
        protected String accountIdentifier;
        @XmlElement(name = "person-name", required = true)
        protected PersonName personName;
        @XmlElement(name = "postal-address", required = true)
        protected PostalAddress postalAddress;
        @XmlElement(name = "electronic-contact", required = true)
        protected ElectronicContact electronicContact;

        /**
         * Gets the value of the accountIdentifier property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getAccountIdentifier() {
            return accountIdentifier;
        }

        /**
         * Sets the value of the accountIdentifier property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAccountIdentifier(String value) {
            this.accountIdentifier = value;
        }

        /**
         * Gets the value of the personName property.
         *
         * @return possible object is
         *         {@link PersonName }
         */
        public PersonName getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         *
         * @param value allowed object is
         *              {@link PersonName }
         */
        public void setPersonName(PersonName value) {
            this.personName = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the electronicContact property.
         *
         * @return possible object is
         *         {@link ElectronicContact }
         */
        public ElectronicContact getElectronicContact() {
            return electronicContact;
        }

        /**
         * Sets the value of the electronicContact property.
         *
         * @param value allowed object is
         *              {@link ElectronicContact }
         */
        public void setElectronicContact(ElectronicContact value) {
            this.electronicContact = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="with-deferments">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}aged-balance"/>
     *                   &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="total-deferred" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="has-expired-deferment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="without-deferments">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}aged-balance"/>
     *                   &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "withDeferments",
            "withoutDeferments"
    })
    public static class Balances {

        @XmlElement(name = "with-deferments", required = true)
        protected KsaBill.Balances.WithDeferments withDeferments;
        @XmlElement(name = "without-deferments", required = true)
        protected KsaBill.Balances.WithoutDeferments withoutDeferments;

        /**
         * Gets the value of the withDeferments property.
         *
         * @return possible object is
         *         {@link KsaBill.Balances.WithDeferments }
         */
        public KsaBill.Balances.WithDeferments getWithDeferments() {
            return withDeferments;
        }

        /**
         * Sets the value of the withDeferments property.
         *
         * @param value allowed object is
         *              {@link KsaBill.Balances.WithDeferments }
         */
        public void setWithDeferments(KsaBill.Balances.WithDeferments value) {
            this.withDeferments = value;
        }

        /**
         * Gets the value of the withoutDeferments property.
         *
         * @return possible object is
         *         {@link KsaBill.Balances.WithoutDeferments }
         */
        public KsaBill.Balances.WithoutDeferments getWithoutDeferments() {
            return withoutDeferments;
        }

        /**
         * Sets the value of the withoutDeferments property.
         *
         * @param value allowed object is
         *              {@link KsaBill.Balances.WithoutDeferments }
         */
        public void setWithoutDeferments(KsaBill.Balances.WithoutDeferments value) {
            this.withoutDeferments = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}aged-balance"/>
         *         &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="total-deferred" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="has-expired-deferment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "agedBalance",
                "totalBalance",
                "futureBalance",
                "dueBalance",
                "overdueBalance",
                "totalDeferred",
                "hasExpiredDeferment"
        })
        public static class WithDeferments {

            @XmlElement(name = "aged-balance", required = true)
            protected AgedBalance agedBalance;
            @XmlElement(name = "total-balance", required = true)
            protected BigDecimal totalBalance;
            @XmlElement(name = "future-balance", required = true)
            protected BigDecimal futureBalance;
            @XmlElement(name = "due-balance", required = true)
            protected BigDecimal dueBalance;
            @XmlElement(name = "overdue-balance", required = true)
            protected BigDecimal overdueBalance;
            @XmlElement(name = "total-deferred", required = true)
            protected BigDecimal totalDeferred;
            @XmlElement(name = "has-expired-deferment")
            protected boolean hasExpiredDeferment;

            /**
             * Gets the value of the agedBalance property.
             *
             * @return possible object is
             *         {@link AgedBalance }
             */
            public AgedBalance getAgedBalance() {
                return agedBalance;
            }

            /**
             * Sets the value of the agedBalance property.
             *
             * @param value allowed object is
             *              {@link AgedBalance }
             */
            public void setAgedBalance(AgedBalance value) {
                this.agedBalance = value;
            }

            /**
             * Gets the value of the totalBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getTotalBalance() {
                return totalBalance;
            }

            /**
             * Sets the value of the totalBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setTotalBalance(BigDecimal value) {
                this.totalBalance = value;
            }

            /**
             * Gets the value of the futureBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getFutureBalance() {
                return futureBalance;
            }

            /**
             * Sets the value of the futureBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setFutureBalance(BigDecimal value) {
                this.futureBalance = value;
            }

            /**
             * Gets the value of the dueBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getDueBalance() {
                return dueBalance;
            }

            /**
             * Sets the value of the dueBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setDueBalance(BigDecimal value) {
                this.dueBalance = value;
            }

            /**
             * Gets the value of the overdueBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getOverdueBalance() {
                return overdueBalance;
            }

            /**
             * Sets the value of the overdueBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setOverdueBalance(BigDecimal value) {
                this.overdueBalance = value;
            }

            /**
             * Gets the value of the totalDeferred property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getTotalDeferred() {
                return totalDeferred;
            }

            /**
             * Sets the value of the totalDeferred property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setTotalDeferred(BigDecimal value) {
                this.totalDeferred = value;
            }

            /**
             * Gets the value of the hasExpiredDeferment property.
             */
            public boolean isHasExpiredDeferment() {
                return hasExpiredDeferment;
            }

            /**
             * Sets the value of the hasExpiredDeferment property.
             */
            public void setHasExpiredDeferment(boolean value) {
                this.hasExpiredDeferment = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}aged-balance"/>
         *         &lt;element name="total-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="future-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="due-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="overdue-balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "agedBalance",
                "totalBalance",
                "futureBalance",
                "dueBalance",
                "overdueBalance"
        })
        public static class WithoutDeferments {

            @XmlElement(name = "aged-balance", required = true)
            protected AgedBalance agedBalance;
            @XmlElement(name = "total-balance", required = true)
            protected BigDecimal totalBalance;
            @XmlElement(name = "future-balance", required = true)
            protected BigDecimal futureBalance;
            @XmlElement(name = "due-balance", required = true)
            protected BigDecimal dueBalance;
            @XmlElement(name = "overdue-balance", required = true)
            protected BigDecimal overdueBalance;

            /**
             * Gets the value of the agedBalance property.
             *
             * @return possible object is
             *         {@link AgedBalance }
             */
            public AgedBalance getAgedBalance() {
                return agedBalance;
            }

            /**
             * Sets the value of the agedBalance property.
             *
             * @param value allowed object is
             *              {@link AgedBalance }
             */
            public void setAgedBalance(AgedBalance value) {
                this.agedBalance = value;
            }

            /**
             * Gets the value of the totalBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getTotalBalance() {
                return totalBalance;
            }

            /**
             * Sets the value of the totalBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setTotalBalance(BigDecimal value) {
                this.totalBalance = value;
            }

            /**
             * Gets the value of the futureBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getFutureBalance() {
                return futureBalance;
            }

            /**
             * Sets the value of the futureBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setFutureBalance(BigDecimal value) {
                this.futureBalance = value;
            }

            /**
             * Gets the value of the dueBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getDueBalance() {
                return dueBalance;
            }

            /**
             * Sets the value of the dueBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setDueBalance(BigDecimal value) {
                this.dueBalance = value;
            }

            /**
             * Gets the value of the overdueBalance property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getOverdueBalance() {
                return overdueBalance;
            }

            /**
             * Sets the value of the overdueBalance property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setOverdueBalance(BigDecimal value) {
                this.overdueBalance = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}person-name"/>
     *         &lt;element ref="{}postal-address" minOccurs="0"/>
     *         &lt;element ref="{}electronic-contact" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "personName",
            "postalAddress",
            "electronicContact"
    })
    public static class BillRecipient {

        @XmlElement(name = "person-name", required = true)
        protected PersonName personName;
        @XmlElement(name = "postal-address")
        protected PostalAddress postalAddress;
        @XmlElement(name = "electronic-contact")
        protected ElectronicContact electronicContact;

        /**
         * Gets the value of the personName property.
         *
         * @return possible object is
         *         {@link PersonName }
         */
        public PersonName getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         *
         * @param value allowed object is
         *              {@link PersonName }
         */
        public void setPersonName(PersonName value) {
            this.personName = value;
        }

        /**
         * Gets the value of the postalAddress property.
         *
         * @return possible object is
         *         {@link PostalAddress }
         */
        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         *
         * @param value allowed object is
         *              {@link PostalAddress }
         */
        public void setPostalAddress(PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the electronicContact property.
         *
         * @return possible object is
         *         {@link ElectronicContact }
         */
        public ElectronicContact getElectronicContact() {
            return electronicContact;
        }

        /**
         * Sets the value of the electronicContact property.
         *
         * @param value allowed object is
         *              {@link ElectronicContact }
         */
        public void setElectronicContact(ElectronicContact value) {
            this.electronicContact = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bill-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="bill-generated" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="bill-start" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="bill-end" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "billDate",
            "billGenerated",
            "billStart",
            "billEnd"
    })
    public static class Cycle {

        @XmlElement(name = "bill-date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar billDate;
        @XmlElement(name = "bill-generated", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar billGenerated;
        @XmlElement(name = "bill-start", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar billStart;
        @XmlElement(name = "bill-end", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar billEnd;

        /**
         * Gets the value of the billDate property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getBillDate() {
            return billDate;
        }

        /**
         * Sets the value of the billDate property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setBillDate(XMLGregorianCalendar value) {
            this.billDate = value;
        }

        /**
         * Gets the value of the billGenerated property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getBillGenerated() {
            return billGenerated;
        }

        /**
         * Sets the value of the billGenerated property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setBillGenerated(XMLGregorianCalendar value) {
            this.billGenerated = value;
        }

        /**
         * Gets the value of the billStart property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getBillStart() {
            return billStart;
        }

        /**
         * Sets the value of the billStart property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setBillStart(XMLGregorianCalendar value) {
            this.billStart = value;
        }

        /**
         * Gets the value of the billEnd property.
         *
         * @return possible object is
         *         {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getBillEnd() {
            return billEnd;
        }

        /**
         * Sets the value of the billEnd property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setBillEnd(XMLGregorianCalendar value) {
            this.billEnd = value;
        }

    }

}
