//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 09:08:39 PM GMT-05:00 
//


package com.sigmasys.kuali.ksa.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receipt-date" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="receipt-time" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="transaction-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="authorization" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="foreign-transaction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="posted-to-account-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="posting-user-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="transaction-type">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transaction-type-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="transaction-type-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "receiptDate",
        "receiptTime",
        "transactionIdentifier",
        "authorization",
        "amount",
        "foreignTransaction",
        "postedToAccountIdentifier",
        "postingUserIdentifier",
        "transactionType"
})
@XmlRootElement(name = "transaction-receipt")
public class TransactionReceipt {

    @XmlElement(name = "receipt-date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receiptDate;

    @XmlElement(name = "receipt-time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar receiptTime;

    @XmlElement(name = "transaction-identifier", required = true)
    protected String transactionIdentifier;

    @XmlElement
    protected String authorization;

    @XmlElement(required = true)
    protected BigDecimal amount;

    @XmlElement(name = "foreign-transaction")
    protected TransactionReceipt.ForeignTransaction foreignTransaction;

    @XmlElement(name = "posted-to-account-identifier", required = true)
    protected String postedToAccountIdentifier;

    @XmlElement(name = "posting-user-identifier", required = true)
    protected String postingUserIdentifier;

    @XmlElement(name = "transaction-type", required = true)
    protected TransactionReceipt.TransactionType transactionType;

    /**
     * Gets the value of the foreignTransaction property.
     *
     * @return possible object is
     *         {@link TransactionReceipt.ForeignTransaction }
     */
    public TransactionReceipt.ForeignTransaction getForeignTransaction() {
        return foreignTransaction;
    }

    /**
     * Sets the value of the foreignTransaction property.
     *
     * @param value allowed object is
     *              {@link TransactionReceipt.ForeignTransaction }
     */
    public void setForeignTransaction(TransactionReceipt.ForeignTransaction value) {
        this.foreignTransaction = value;
    }

    /**
     * Gets the value of the transactionType property.
     *
     * @return possible object is
     *         {@link TransactionReceipt.TransactionType }
     */
    public TransactionReceipt.TransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     *
     * @param value allowed object is
     *              {@link TransactionReceipt.TransactionType }
     */
    public void setTransactionType(TransactionReceipt.TransactionType value) {
        this.transactionType = value;
    }

    public XMLGregorianCalendar getReceiptDate() {
        return receiptDate;
    }

    public void setReceiptDate(XMLGregorianCalendar receiptDate) {
        this.receiptDate = receiptDate;
    }

    public XMLGregorianCalendar getReceiptTime() {
        return receiptTime;
    }

    public void setReceiptTime(XMLGregorianCalendar receiptTime) {
        this.receiptTime = receiptTime;
    }

    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    public void setTransactionIdentifier(String transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
    }

    public String getAuthorization() {
        return authorization;
    }

    public void setAuthorization(String authorization) {
        this.authorization = authorization;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getPostedToAccountIdentifier() {
        return postedToAccountIdentifier;
    }

    public void setPostedToAccountIdentifier(String postedToAccountIdentifier) {
        this.postedToAccountIdentifier = postedToAccountIdentifier;
    }

    public String getPostingUserIdentifier() {
        return postingUserIdentifier;
    }

    public void setPostingUserIdentifier(String postingUserIdentifier) {
        this.postingUserIdentifier = postingUserIdentifier;
    }

    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="native-amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "nativeAmount",
            "currency"
    })
    public static class ForeignTransaction {

        @XmlElement(name = "native-amount", required = true)
        protected BigDecimal nativeAmount;
        @XmlElement(required = true)
        protected String currency;

        /**
         * Gets the value of the nativeAmount property.
         *
         * @return possible object is
         *         {@link BigDecimal }
         */
        public BigDecimal getNativeAmount() {
            return nativeAmount;
        }

        /**
         * Sets the value of the nativeAmount property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setNativeAmount(BigDecimal value) {
            this.nativeAmount = value;
        }

        /**
         * Gets the value of the currency property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transaction-type-identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="transaction-type-name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "transactionTypeIdentifier",
            "transactionTypeName"
    })
    public static class TransactionType {

        @XmlElement(name = "transaction-type-identifier", required = true)
        protected String transactionTypeIdentifier;

        @XmlElement(name = "transaction-type-name", required = true)
        protected String transactionTypeName;

        /**
         * Gets the value of the transactionTypeIdentifier property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransactionTypeIdentifier() {
            return transactionTypeIdentifier;
        }

        /**
         * Sets the value of the transactionTypeIdentifier property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransactionTypeIdentifier(String value) {
            this.transactionTypeIdentifier = value;
        }

        /**
         * Gets the value of the transactionTypeName property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getTransactionTypeName() {
            return transactionTypeName;
        }

        /**
         * Sets the value of the transactionTypeName property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTransactionTypeName(String value) {
            this.transactionTypeName = value;
        }

    }

}
